### ISSUE TITLE
Add an option to turn off source control in func init

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#104]
Per discussion in https://github.com/Azure/azure-functions-cli/issues/97#issuecomment-290202515. Add a switch --no-source-control to `func init`. Shortcut --noscm

**Comment by SteveALee** [comment]
or maybe turn "on"? :)

I'm not sure what the most comment required is. Given the easy Azure deploy from a git repo I guess you might be right.

**Comment by lindydonna** [comment]
@SteveALee Good point, I wasn't sure what the default should be either!

**Comment by SteveALee** [comment]
@lindydonna Actuall I changed my mind. `git init` is trivial to do if required and we should separate concerns :) Or are you doing more than a simple 'git init'?

**Comment by lindydonna** [comment]
@SteveALee We add appsettings.json to .gitignore, but that could certainly be a separate step.
