### ISSUE TITLE
Odd errors when starting a function that monitors blob storage (but it still works)

### ISSUE THREAD

**Issue by pugwonk** [Azure/azure-functions-cli#105]
I've written a function which monitors blob storage (i.e. doesn't take any HTTP input). When I execute:

`func run getWorkbook`

I get the little host window popping up, but it's full of errors:

```
Executing 'Functions.getWorkbook' (Reason='This function was programmatically called via the host APIs.', Id=e0071b5f-a5f8-4b74-a721-48f3832d3665)
A ScriptHost error has occurred
Exception while executing function: Functions.getWorkbook. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'jsonBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.
Exception while executing function: Functions.getWorkbook. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'jsonBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.

Exception while executing function: Functions.getWorkbook
Exception while executing function: Functions.getWorkbook. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'jsonBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.
Executed 'Functions.getWorkbook' (Failed, Id=e0071b5f-a5f8-4b74-a721-48f3832d3665)
mscorlib: Exception while executing function: Functions.getWorkbook. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'jsonBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.
  Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is 'e0071b5f-a5f8-4b74-a721-48f3832d3665'
mscorlib: Exception while executing function: Functions.getWorkbook. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'jsonBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.
Job host started

```
After all this, the function actually works fine when I upload something to blob storage.

I think this is because the CLI is trying to _execute_ my function with the wrong parameters. But I don't want it to execute - I just want it to monitor the blob.

This is somewhat annoying as I can't tell immediately whether all these errors are new ones I've just created, or the old ones that came up every time. Is it possible to have the CLI not try to actually execute the function if it triggers off something that isn't HTTP?

**Comment by beufordy3k** [comment]
@pugwonk are you not using,
```
func host start
```
for a reason?  `func run` afaik and understand is meant to execute your function, but a function that responds to monitored events is something handled by the host.

**Comment by SteveALee** [comment]
That's right, `func run` starts the host (which gets all your functions ready to be triggered) and then calls the function you specify. It's similar to using the Function Run feature in the portal and makes most sense with HTTP trigger functions when you pass a payload to simulate an HTTP event..

**Comment by beufordy3k** [comment]
Yep, so if @pugwonk is looking to have his function respond to blob storage events and not manually invoke his function directly, sounds like he will probably want
```
func host start
```

**Comment by pugwonk** [comment]
Argggh. Thank you very much! It would be great if the README could be modified a little to have a "here are the three commands you need to get started" at the beginning of it. I would offer to submit a PR but, erm, I've clearly demonstrated that the three commands I needed to get started were not the correct ones. Also the error messages that come up when one _does_ do what I did are extremely confusing - I spent quite a while trying to work out what was wrong with my function.json before realising that the darned thing was actually happily running.

**Comment by lindydonna** [comment]
@pugwonk Thanks for the feedback, we'll improve the documentation. Unfortunately, it's not easy to provide a better error message in the CLI, as the error comes from the underlying Functions runtime.

**Comment by lindydonna** [comment]
Documentation is now available here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local
