### ISSUE TITLE
Ensure binding redirects in CLI match those in Script

### ISSUE THREAD

**Issue by beufordy3k** [Azure/azure-functions-cli#106]
Hey so I'm not sure if this should go just here or in the [https://github.com/Azure/azure-webjobs-sdk-script](https://github.com/Azure/azure-webjobs-sdk-script) repo as well.

I'm running into an issue when using Azure Functions as the front-end for existing (.NET 4.6.2) code that is a bit more complex with nuget refs and dependencies.

It appears that `func.exe` has a standard set of assembly binding redirects in it's `func.exe.config` for things like `Newtonsoft.Json` 0.0.0.0-9.0.0.0 binding redirect. (*incidentally can we bump that to 10.0.0.0 now?*)

So when you add a nuget reference in your .net assembly (that you are referencing in a `run.csx` for example) you **MUST** leave the underlying dependencies at the *PRECISE* version that the nuget package has as a dependency, otherwise when your code attempts to use the library referenced it will be unable to load that library's dependencies and will result in a runtime error due to binding issues.

For Example:
```
Pathoschild.Http.FluentClient 3.0.0
```
in .NET 4.5.2, has a dependency of,
```
System.Net.Http 4.0.0
```
If I want to uplift `System.Net.Http` to the latest 4.3.0, I cannot as any attempt to use the FluentClient will result in a binding failure,

```csharp
var client = new FluentClient("http://10.0.0.10/api/");
```
^-- will fail without binding redirect.

I guess what I'm asking for is a way to have the func.exe dynamically load additional binding redirects from a host-level  `app.config` or `web.config` file?

Please let me know if further detail and/or a full example are required. Thanks!

**Comment by lindydonna** [comment]
@beufordy3k This is a feature for the Functions script runtime in https://github.com/Azure/azure-webjobs-sdk-script.

For the CLI, we'll verify that our binding redirects match those in the Functions runtime.

**Comment by beufordy3k** [comment]
@lindydonna ok, thanks for the update! 
I'll dig into it further and open an issue over in that repo as needed.
