### ISSUE TITLE
func azure command tries to log in to azure

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#112]
Func azure used to just print out the help text. Now it tries to log in. If I close the login window, I get the following exception:

> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ArmManager (ReflectionActivator), Services = [Azure.Functions.Cli.Arm.IArmManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(ARMClient.Authentication.IAuthHelper, ARMClient.Library.IAzureClient, Azure.Functions.Cli.Interfaces.ISettings)' on type 'ArmManager'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.)

**Comment by ahmelsayed** [comment]
crap, right... This is a regression from 5f3978f1dadcc7052e693168dac226ee375e9f65. I'll have to think about it.
