### ISSUE TITLE
CLI "Save As" or "Clone" for a function, or function app to get local clones for sync with azure portal or Allow publishing the same function multiple times with different name

### ISSUE THREAD

**Issue by tmtso** [Azure/azure-functions-cli#115]
While working with CLI and publishing my function for different customer, they asked me to provide the function twice (one for their productive settings and one for their development). 
Afaik I have no option to publish the same function twice without copying the whole project and rename it, which makes it necessary to make double work if I want to change something in my code. 

So a new feature request would be to make it possible to upload a function twice and the possibility to rename the function in this process to see the difference inside the portal.

**Comment by SteveALee** [comment]
@tmtso 

Probably a more general CLI "Save As" or "Clone" for a function, or rather function app,  might be more useful to get a local clone that you can then sync.

However,  I think this use case is really part of the broader topic of needing the [App Service deployment slots feature](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-staged-publishing) to work with functions.

You could add your +1 to https://github.com/Azure/Azure-Functions/issues/45

BTW have you seen this on CI?- https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment.

**Comment by tmtso** [comment]
@SteveALee 

Yeah, that's my first post here on Github (and english is not my native language^^) so I will take your text and rewrite my entry post. 

I looked at CI and my problem with this is, that I'm deploying from my TFS but can't connect other customers which have their own azure portal (maybe I'm doing something wrong, but atm I'm using the normal publish feature to deploy to our customers)

**Comment by SteveALee** [comment]
@tmtso oh wow, there was no need at all to rewrite your issue! I was not in anyway criticizing your post. Your English is excellent. Rather, I was just commenting and giving some additional thoughts from my perspective! 

I'm not a TFS user so I you know much more than me. :)

I'm not part of the Azure team and I'm sure they will have firm views on the matter given their plans ;)

**Comment by lindydonna** [comment]
@SteveALee is right, you'd want to deployment slots for this feature. I'm closing this issue, as it's not directly related to the CLI.

We're actively working on deployment slots.
