### ISSUE TITLE
Error calling the functions host: ServiceUnavailable / The host is taking longer than expected to start

### ISSUE THREAD

**Issue by picarsite** [Azure/azure-functions-cli#121]
After updating to 1.0.0-beta.94, I can not run my function anymore. I uninstalled and installed the azure-functions-cli multiple times but I does not help.

I get the following errors:

> Error calling the functions host: ServiceUnavailable

and

> Listening on http://localhost:7071/
> Hit CTRL-C to exit...
> Reading host configuration file 'C:\Users\myuser\Desktop\myfunction\host.json'
> Generating 1 job function(s)
> Starting Host (HostId=86d93bf44b684e12a5375b9b0c36427d, Version=1.0.10826.0, ProcessId=4412, Debug=False, Attempt=0)
> Found the following functions:
> Host.Functions.myfunction
> 
> Job host started
> The host is taking longer than expected to start.
> The host is taking longer than expected to start.

Is it possible to determine the exact problem?

Best regards

**Edit:**

Tried with my old version @1.0.0-beta.91. It works with the old one.

**Comment by lindydonna** [comment]
Interesting, it could be an issue with the port being reserved by another process. Try passing in a port explicitly `func host start -p 7072`

**Comment by SimoneBWS** [comment]
I have the same issue after update v1.0.0-beta.94.
Passing a port explicitly `func host start -p 7072` works. Is is possible to set into func.exe.config (or in other location) to define a different default port?

**Comment by lindydonna** [comment]
@SimoneBWS We have an open issue in the CLI repo to allow specifying a port in appsettings.json: https://github.com/Azure/azure-functions-cli/issues/79

**Comment by gbenshim** [comment]
I'm facing a similar issue, i'm in debug mode in visual studio, i don't understand what it means "Try passing in a port explicitly func host start -p 7072" (i'm really new with Azure).

Can you explain how to do it? I can't find any setting that allows me to control the start parameters/arguments.

**Comment by lindydonna** [comment]
@gbenshim My instructions were about calling the CLI explicitly. You can do this if you create a web project with a custom start action, or run the CLI yourself from the command line.

See https://aka.ms/precompiled-functions
