### ISSUE TITLE
Calling a Manual Trigger function just returns "Error calling the functions host: Unauthorized"

### ISSUE THREAD

**Issue by jonathanfishbein1** [Azure/azure-functions-cli#124]
This is my manual function

`let Run(input: string) =
  input
`
and this is how I call it

`node_modules\.bin\azurefunctions run ManualTrigge
rFSharp --c "Hello"`

**Comment by mathias-brandewinder** [comment]
I am observing something similar. Creating any vanilla F# function from the CLI, for instance HttpRequest one, and whenever I try to run anything, I get `Error calling the functions host: Unauthorized`. The odd thing is, that works perfectly fine on another machine. I couldn't pinpoint the difference yet between the machines setup.

**Comment by mathias-brandewinder** [comment]
I did a fresh install on 2 identical VMs:
VM1
Azure Functions Cli (1.0.0-beta.9)
Function Runtime Version: 1.0.0.0
VM2
Azure Functions Core Tools (1.0.0-beta.95)
Function Runtime Version: 1.0.10917.0
Creating and running the basic HttpTrigger function in F#, following this example: https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/, works like a champ on VM1, and fails on VM2.

**Comment by mathias-brandewinder** [comment]
Sounds like this issue: http://stackoverflow.com/q/43685911/114519

**Comment by ahmelsayed** [comment]
this issue should be fixed by https://github.com/Azure/azure-webjobs-sdk-script/pull/1463 in the runtime. will need to update the dependency here once that package is released.

**Comment by ahmelsayed** [comment]
Fix should be out in 1.0.0.beta.96. Please give that a try and let me know if you see any other issues regarding this.
