### ISSUE TITLE
Timer lease is not released when shutting down the CLI

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-cli#126]
This comes from [forum thread](https://social.msdn.microsoft.com/Forums/en-US/90878d1e-d2cd-4aa4-b3f5-3bee150f0c1a/local-function-debugging-for-timer-function-function-never-starts?forum=AzureFunctions) and I reproed it as well.

- Create a timer function that runs every second
- Run it
- Close the CLI and run it again

Result: it can take up to 60 seconds for the timer to start kicking in

@fabiocav and @paulbatum think it happens because the CLI gets killed without having a chance to release the lease.

**Comment by lindydonna** [comment]
See also https://github.com/Azure/Azure-Functions/issues/281

**Comment by lindydonna** [comment]
Duplicate https://github.com/Azure/azure-functions-cli/issues/55
