### ISSUE TITLE
func.exe terminates after error when debugging as a web project

### ISSUE THREAD

**Issue by nitro52** [Azure/azure-functions-cli#132]
Hi,
I'm trying to setup a project as a web project based on these instructions

https://blogs.msdn.microsoft.com/appserviceteam/2017/03/16/publishing-a-net-class-library-as-a-function-app/
and 
https://github.com/lindydonna/FunctionsAsWebProject

I created a new ASP.net web application using the blank template, went through all nuget packages and installed missing ones. Then copied the sample function into the new project, setup the project settings to start func.exe as the instructions say. From what i can see my new project is the same as the sample one. However when i try running it either with debugging or without the host starts but it shows a red error for a split second and then terminates, its not long enough to see what is wrong.

I've work around the issue, this is just a FYI task, if this is likely to be the dev environment moving forward it would be good if you can setup the host to not exit on errors or someout output the console somewhere. 

For now i was able to run the sample fine so i just renamed it, changes the namespaces and updated function.json. This seems to work. The only difference i can see is that the sample opens in VS2017 when i was using VS2015

**Comment by nitro52** [comment]
Think i just figured out what was wrong with my attempt, there was a appsettings.json and host.json in the project dir that wasn't included in the project so i didn't see them.

**Comment by lindydonna** [comment]
Yes, that was the issue. In the future, you can add the flag --pause-on-error to func.exe to see the error message in the command window.

**Comment by cc-talha** [comment]
I guess flag --pause-on-error isnt working at my side.. 
adding flag like 
func run functionname --pause-on-error
still terminal close and no error message on cmd or powershell
any guess ?
