### ISSUE TITLE
CLI will fail if the npm module path contains non-ascii characters

### ISSUE THREAD

**Issue by eNeRGy164** [Azure/azure-functions-cli#134]
I installed the CLI using `npm i -g azure-functions-core-tools` which installs it in my user profile using the following path: `C:\Users\Michaël\AppData\Roaming\npm\node_modules\azure-functions-core-tools`

When running `func host start` it fails with the following error:
```
module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\Micha�l\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

You can see it is encoding the path wrong.

Funny note: If I remove everything in the roaming folder the error does show the correct encoded path:
`Error: Cannot find module 'C:\Users\Michaël\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js'`

**Comment by eNeRGy164** [comment]
I've tried to trace the issue, and it seems it goes wrong when loading Edge.js.
When skipping the method `DummyEdgeInit` in the `StartHostAction` class the host launches without error.

**Comment by eNeRGy164** [comment]
Seems an issue in EdgeJs.

Created a [pull request](https://github.com/tjanczuk/edge/pull/555) with a workaround

**Comment by lindydonna** [comment]
Closing as it's an Edge bug, not CLI. We'll merge the update to Edge when it's committed.
