### ISSUE TITLE
Why does "func host start" assume bin?

### ISSUE THREAD

**Issue by jaredcnance** [Azure/azure-functions-cli#136]
It seems that `func host start` command looks for a function to exist in `.\bin\`. This is not entirely intuitive, especially since it is not documented (at least as far as I can tell). It would make more sense if the CLI executed in the current directory.

**Comment by ahmelsayed** [comment]
Not sure what you mean. It doesn't really know anything about a bin folder. What are you trying to do and what are you seeing?

**Comment by jaredcnance** [comment]
So, if I have the following directory structure:
```
/app
/app/bin
/app/bin/app.dll
/app/bin/function.json
/app/host.json
/app/function.json
```

and function.json looks like:

```json
{
  "scriptFile": "app.dll",
  "entryPoint": "App.Main.Run",
  "disabled": false, ...
}
```

Running `func host start` in bin (where the dll is located) results in the following response:

[5/15/2017 3:15:59 PM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

Also, if I remove the function.json file from the root, so that it only exists in bin, I get the same result.

**Comment by ahmelsayed** [comment]
I see.

The function runtime expects the folder structure to look something like this:

```
C:.
|   host.json
|
+---Function1
|       function.json
|
\---Function2
       function.json
```

This is the convention of the file layout. the act of having a folder with a `function.json` is what makes it a "function".

So When you run `func host start` it assumes that you have a function called `bin`. 

What's odd is that it should travel up the tree and run in the app root (which ever folder has `host.json` in it).  Which version are you using?

**Comment by jaredcnance** [comment]
Ah I see and that makes sense

Azure Functions Core Tools (1.0.0-beta.96)
Function Runtime Version: 1.0.10955.0

**Comment by ahmelsayed** [comment]
yep! that explains it :) 
I'm glad you were able to figure this out. I'll close this issue than!
