### ISSUE TITLE
Authentication error prints stacktrace

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#137]
As reported by Joe Raio:

> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ArmManager (ReflectionActivator), Services = [Azure.Functions.Cli.Arm.IArmManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(ARMClient.Authentication.IAuthHelper, ARMClient.Library.IAzureClient, Azure.Functions.Cli.Interfaces.ISettings)' on type 'ArmManager'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.)

Steps to reproduce:
•	Open cmd prompt
•	func azure
•	I enter my Microsoft email
•	It then says redirecting you to your organizations sign in page.. then the error notes.

**Comment by ahmelsayed** [comment]
fixed in bf6c15693f1e1e7654d553d90cd9447807832585
