### ISSUE TITLE
KeyVault incompatible with Functions

### ISSUE THREAD

**Issue by Workshop2** [Azure/azure-functions-cli#138]
Hello,

I have been banging my head against a table trying to get Key Vault working in my function.

I receive the following error:
Method not found: 'Void Microsoft.Azure.KeyVault.KeyVaultClient..ctor(AuthenticationCallback, System.Net.Http.DelegatingHandler[])

I am using the latest versions in which this should be fixed - any help would be great (I think the Azure CLI/SDK is using an older version of this library & System.Net.Http).

Example:
https://github.com/Workshop2/azure-function-with-keyvault

**Comment by Workshop2** [comment]
Looks like the libraries included in the `Azure.Functions.Cli` are overriding anything in the Azure Function. These libraries are out of date.

Can you update the following packages
 - System.Net.Http
 - Microsoft.Azure.KeyVault

**Comment by lindydonna** [comment]
@Workshop2 What version of the Azure CLI are you using?  We updated our binding redirects in 0.97.

**Comment by Workshop2** [comment]
Aha, my VS updated to 0.97 and it works fine. Thanks for the help
