### ISSUE TITLE
func new returns Running with stdin\stdout redirected error

### ISSUE THREAD

**Issue by alexjamesbrown** [Azure/azure-functions-cli#144]
When running `func new` I get this error

> #Running with stdin\stdout redirected. Command must specify --language, --template, and --name explicitly.
> See 'func help function' for more details

... not the Yeoman menu I was expecting

(Running this on Windows)

**Comment by ahmelsayed** [comment]
we're no longer using yeomen for the templates, mostly due to yeomen startup time.
What shell are you using to run the cli? it looks like your shell has stdin and stdout redirected, so we can't run the interactive menu, and you have to specify all the parameters on the commandline.

**Comment by alexjamesbrown** [comment]
Was just standard cmd in windows...
Not sure why it would be redirected?

**Comment by ahmelsayed** [comment]
That's odd.... You should get an interactive menu. Is this something you can repro consistently? 
![2017-05-24_13-36-47](https://cloud.githubusercontent.com/assets/645740/26424445/12702760-4086-11e7-8075-034e2027053c.gif)

**Comment by alexjamesbrown** [comment]
yes, could constantly reproduce it....

All i did, was:

    npm i -g azure-functions-cli

`func init` worked fine....

**Comment by ahmelsayed** [comment]
btw, the package name was changed to [`azure-functions-core-tools`](https://www.npmjs.com/package/azure-functions-core-tools). installing `azure-functions-cli` should have a deprecation message, and I'm planning to update the cli there to point to the new name. 

Sorry, just to make sure I understand correctly, are you saying you got it to work now?

**Comment by alexjamesbrown** [comment]
AHh, I'm wondering if I installed azure-functions-cli?
I'm not currently on my work laptop - i can certainly try that tomorrow morning -

how would I uninstall azure-functions-cli?

**Comment by ahmelsayed** [comment]
`npm uninstall -g azure-functions-cli`

**Comment by alexjamesbrown** [comment]
yeah, that was it -
uninstalling, then installing `azure-functions-core-tools` now presents the menu

I think I was probably following outdated tutorials before...
