### ISSUE TITLE
A 'Task was canceled' error on publish C# project with many packages

### ISSUE THREAD

**Issue by khaale** [Azure/azure-functions-cli#147]
It seems like `packages` folder (which tends to be huge even for small solutions) is included into directory archive file and makes it too large. 

Eventually, with 400Mb packages, I became receiving 
> Task was canceled

error on `func azure functionapp publish`. That was fixed just by deleting `packages` folder.

Is it possible excluding `packages` from uploaded archive (maybe optionally)?

**Comment by ahmelsayed** [comment]
aha. Thanks for the repro. I have been seeing reports about this but couldn't get it to repro myself, so I wasn't sure what's going on. I just needed to increase the timeout of upload request as currently it's too short for large uploads. With that said, I think I can respect .gitignore file (or similar format ignore file) during publishing as well. I think that would be a better option than adding a yet another command line argument to pass in folders or files you don't want to include.

**Comment by khaale** [comment]
Yes, adding something like `.cloudignore` with `.gitignore`-like format looks handy, at least for pet-projects usage. `.gitignore` itself cannot be used there, as it usually ignores all the binaries (and also it could be not so easy to support the whole [gitignore format spec](https://git-scm.com/docs/gitignore)  with `/**` etc.

As a workaround I will go with simple PowerShell script which copies all the needed into staging directory and calls publish from there. To be honest, I think that this way will become more popular for real production usage (not just for pet projects, but for enterprise).

**Comment by lindydonna** [comment]
Timeout increased, and should fix the original issue.

For the other request, please open another issue to track the feature request.
