### ISSUE TITLE
Cannot start cli on linux

### ISSUE THREAD

**Issue by frozenbubble** [Azure/azure-functions-cli#149]
I cannot start the cli on linux. It worked fine when I tried it on windows but on linux I always get the following error (no matter which command I try it with):

`/usr/bin/env: ‘node\r’: No such file or directory`

node version: v7.10.0
npm version: 5.0.2
OS: Arch Linux

I found this iothub-explorer issue that perfectly describes my problem: https://github.com/Azure/iothub-explorer/issues/6

**Comment by SteveALee** [comment]
@frozenbubble At present this CLI is Windows cmd only. As the [README](https://github.com/Azure/azure-functions-cli/blob/master/README.md) states, this is due the Functions host layer.

**Comment by frozenbubble** [comment]
Ah my bad, I jumped straight to the usage section. Thanks.

**Comment by lindydonna** [comment]
Closing as the CLI is not yet cross-platform. Please watch this issue: https://github.com/Azure/Azure-Functions/issues/98

**Comment by Hosar** [comment]
I also want to run the CLI on Linux @lindydonna
