### ISSUE TITLE
Local emulator doesn't work as expected with "UseDevelopmentStorage=true"

### ISSUE THREAD

**Issue by mathias-brandewinder** [Azure/azure-functions-cli#150]
Trying to run Azure Functions locally using the Azure Storage Emulator. When I set manually 
`"AzureWebJobsStorage": "UseDevelopmentStorage=true"` in `local.settings.json`, I get a connection string error. However, when I add it through the CLI, with `func settings add AzureWebJobsStorage UseDevelopmentStorage=true`, everything works as expected, but the `local.settings.json` file becomes:

```
{
  "IsEncrypted": true,
  "Values": {
    "AzureWebJobsStorage": "AQAAANCMnd//snip for brevity//"
  },
  "ConnectionStrings": {}
}
```

Is setting the Value to "UseDevelopmentStorage=true" manually supposed to work? Am I misunderstanding something?

Versions:
Azure Functions Core Tools (1.0.0-beta.97)
Function Runtime Version: 1.0.10955.0
Storage Emulator CLI 4.6.0.0

**Comment by lindydonna** [comment]
If the IsEncrypted flag is set to "true", then you can only set values through the CLI. If you want to edit by hand, you should decrypt the file with `func settings decrypt`. Also, in CLI beta.99, you should see a better error message.
