### ISSUE TITLE
Recommendation to run CLI headless for automated tests

### ISSUE THREAD

**Issue by mathias-brandewinder** [Azure/azure-functions-cli#151]
I can run manually sequences of operations in the CLI. What I would like, however, is to write some of these sequences as F# script I could run headless, using only local resources (Azure Storage Emulator), to have some integration tests. However, running the CLI via `System.Diagnostics.Process()` is not very convenient. Would you have some advice or guidance on how to approach this, the goal being to have local integration tests of a function app?

**Comment by lindydonna** [comment]
I would recommend powershell scripts that are run with the `--no-interactive` flag.
