### ISSUE TITLE
 error FS39: The namespace 'ApplicationInsights' is not defined

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-functions-cli#152]
Hi,

3 Months ago I added App Insights to an af app and all worked as designed, locally & cloud: dev & test. Now however, when it is called up on (cloud, not locally) it produces this error:

```
2017-06-07T13:38:16.778 D:\home\site\wwwroot\JobCreate\run.fsx(13,16): error FS39: The namespace 'ApplicationInsights' is not defined
2017-06-07T13:38:16.778 D:\home\site\wwwroot\JobCreate\run.fsx(14,16): error FS39: The namespace 'ApplicationInsights' is not defined
2017-06-07T13:38:16.778 D:\home\site\wwwroot\JobCreate\run.fsx(15,16): error FS39: The namespace 'ApplicationInsights' is not defined
2017-06-07T13:38:16.778 D:\home\site\wwwroot\JobCreate\run.fsx(41,25): error FS39: The type 'TelemetryClient' is not defined
```

Lines 13-15 below:
```
13: open Microsoft.ApplicationInsights
14: open Microsoft.ApplicationInsights.DataContracts
15: open Microsoft.ApplicationInsights.Extensibility
```

Line 41:
```
let telemetry = new TelemetryClient(InstrumentationKey = ConfigurationManager.AppSettings.["APPINSIGHTS_INSTRUMENTATIONKEY"]) 
```

project.json:

```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.ApplicationInsights": "2.2.0"
      }
    }
  }
}
```

I have read this article - https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview) - several times and it didn't help.

What I am doing wrong?

Warmest regards,

Garrard.

**Comment by lindydonna** [comment]
Are you running this locally or in Azure?  If it's in Azure, I recommend 
[MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so).

**Comment by garrardkitchen** [comment]
Hi @lindydonna, yes, the error is from Azure. On my dev machine it works fine. I've Azure Functions CLI 0.99 installed there for Azure Functions development.  I tend to develop / debug locally with all the Azure Functions bits and pieces then push to repo for it then to be sync'd with Azure.  The reason I included notes above about dev & test is that we've a number of environment we're running this with and without any code changes for a few months, it suddenly stopped working.  Do I need to target different version in Azure via app settings or something?

**Comment by fabiocav** [comment]
@garrardkitchen I have a suspicion, but to confirm, can you move your AI package reference to 2.3.0 and retry?

**Comment by garrardkitchen** [comment]
HI @fabiocav, I appreciate the suggestion. I will definitely try this and let you know.

**Comment by garrardkitchen** [comment]
Hi @fabiocav, success!  Your suggestion did the trick.  Many thanks.

Garrard.
