### ISSUE TITLE
Debugging using the Azure Function Core Tools fails for C#

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-functions-cli#153]
I'm testing the latest Core tools on my local machine and debugging C# Functions is failing. The function runs but the breakpoint is never hit in VS Code. Steps to recreate:

```
c:\Projects\test>func run HttpTriggerCSharp -c "{\"name\": \"Debugging!\"}" --debug
Debugger launching...
Setup your break points, and hit continue!
NOTE: the 'func run' command only supports POST for HTTP triggers. For other verbs, consider a REST client like cURL or Postman.
Response Status Code: OK
"Hello Debugging!"
```
This throws the following error message
![2017-06-07_19-55-41](https://user-images.githubusercontent.com/4126750/26896282-15584868-4bbc-11e7-87da-cf6647542d32.png)

I choose to not debug and continue. Function completes but I never get a hit on my breakpoint. Instead, I get the following error message

![file](https://user-images.githubusercontent.com/4126750/26896347-4e73dc3e-4bbc-11e7-9fd3-ad82044e980f.jpeg)

I hope this is related to something wrong with my machine and not the tools. But I tried a few times and it failed.

Also, current tooling from node.js perspective:

```
c:\Projects\test>npm version
{ npm: '4.1.2',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.5.0',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.10.2',
  v8: '5.4.500.48',
  zlib: '1.2.8' }
```

**Comment by lindydonna** [comment]
You can't debug C# functions in VS Code, you have to use Visual Studio. This is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#run-functions-locally
