### ISSUE TITLE
Using 'func host start' on a fresh function app (and existing ones) outputs "Error updating ConfigurationManager.."

### ISSUE THREAD

**Issue by Butternubs** [Azure/azure-functions-cli#158]
We're currently developing some Azure functions using the latest Visual Studio Preview (15.3) and the latest Azure Function CLI, however, every time we run "func host start" through cmd, rather than through Visual Studio, we get "Error updating ConfigurationManager.AppSettings" and "Error updating ConfigurationManager.ConnectionStrings", which in turn means the app can't access any of the settings/connection strings that have been set.

Furthermore, when using "func host start --debug vs" and inspecting the app settings and connection strings using System.Configuration.ConfigurationManager in c#, there are no connection strings, but there are 2 app settings, one which is AzureWebJobsStorage and the other is "heheh", which has the value of IIII for some reason.

I've searched through all of the projects and run them all in isolation, but they all run into this issue.

I haven't seen this issue anywhere else.

![app settings heheh](https://user-images.githubusercontent.com/9280620/26975575-4a9be45a-4d18-11e7-9716-b31dba950bf5.PNG)
![app settings](https://user-images.githubusercontent.com/9280620/26975577-4a9f211a-4d18-11e7-82b8-b786c3e4027f.PNG)
![cap](https://user-images.githubusercontent.com/9280620/26975576-4a9f60bc-4d18-11e7-8927-33d02f81ee83.PNG)

Update: this is fixed by running cmd in Administrative mode, more helpful error messages would be useful rather than the catch-all.

**Comment by ThomasArdal** [comment]
I just spent something like half a day figuring out a similar issue. When debugging my function from Visual Studio, the appsettings accessed through ConfigurationManager.AppSettings, would sometimes switch between function apps. So local.settings.json values from project a would go into project b etc. I didn't help to start Visual Studio as administrator. The only working solution I found, where to start all functions in a cmd run as administrator.

Thank you for sharing.
