### ISSUE TITLE
Enable CLI to locally host function over HTTPS

### ISSUE THREAD

**Issue by garrytrinder** [Azure/azure-functions-cli#162]
I've searched the documentation but can't seem to find out if this is possible?

**Comment by ahmelsayed** [comment]
can you try `func host start --useHttps`? type `func help host` for more details. It will prompt you to install an [auto-generated cert](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Helpers/SecurityHelpers.cs#L81) for localhost to bind https to.

**Comment by lindydonna** [comment]
Yes, and it's documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#run-functions-locally

**Comment by garrytrinder** [comment]
Awesome, thanks for the help @ahmelsayed & @lindydonna

**Comment by SDP190** [comment]
Using `func host start --useHttps` would bind only to localhost, but cannot be accessed from Network IP address.
