### ISSUE TITLE
Can't run func in WSL

### ISSUE THREAD

**Issue by cfjedimaster** [Azure/azure-functions-cli#167]
I'm using `func` in WSL and every option I try gives:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn mono /usr/local/lib/node_modules/azure-functions-core-tools/bin/func.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by lindydonna** [comment]
Are you using a native module?

**Comment by lindydonna** [comment]
Oh, nevermind, you're using the mono package. It is experimental and only works for C#. We are porting the runtime to .NET Core, which will provide proper cross-plat support.  

In the meantime, you should use the Core Tools on Windows.

**Comment by ahmelsayed** [comment]
yeah, sorry we used to have a nice error message for non-windows that I removed. I thought just setting the `os` property in package.json would warn about non-windows install.

**Comment by cfjedimaster** [comment]
"you're using the mono package. It is experimental and only works for C#"
To be clear though, I'm following the directions here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

Which says "You can use your favorite code editor and local development tools to run the Azure Functions runtime locally. Trigger on events in Azure and debug C# and JavaScript functions."

And all I'm trying to do really is "push" up the files to Azure so language shouldn't matter I'd think. 

"Core Tools on Windows" - No idea what that is. Do the Azure Functions docs mention that? Cuz they had led me to the link I shared.

**Comment by lindydonna** [comment]
@cfjedimaster Good point, I thought we had a disclaimer that it only works on Windows. I filed this doc issue to fix: https://github.com/Azure/Azure-Functions/issues/369

When I said "Core Tools," I meant the "Azure Functions Core Tools". We sometimes call it the CLI, but Core Tools is the real name. That term is mentioned in the document.

The Core Tools are written in C#, so we'd have to support .NET Core. This is work in progress and you should see a preview in the next few months.

**Comment by lindydonna** [comment]
@cfjedimaster We'll also improve the error message if you try to run on other platforms. See #168.
