### ISSUE TITLE
Core tools host defaults to XML for HTTP responses

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-cli#170]
### Issue
Requests to HTTP triggers in core tools result in XML responses. This is different from production, where the default is JSON.  I suspect the root cause is some difference in how the underlying Web API host is configured.

### Repro
1. Create an HTTP trigger which does something similar to the following:

```
HttpResponseMessage response = request.CreateResponse(
    HttpStatusCode.Accepted,
    new
    {
        id = instanceId,
        statusQueryGetUri = statusQueryGetUri,
        sendEventPostUri = sendEventPostUri,
        terminatePostUri = terminatePostUri
    });
response.Headers.Location = statusQueryGetUri;
return response;
```

2. Call the HTTP API **without** specifying an `Accept` header.

### Expected
Result is JSON, just like it is in Azure today.

### Actual
Result is XML, which is different from Azure and in general is less useful.

**Comment by ahmelsayed** [comment]
I can't repro this. 
This is my function code

```csharp
public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    return req.CreateResponse(HttpStatusCode.Accepted, new
    {
        id = "instanceId",
        statusQueryGetUri = "statusQueryGetUri",
        sendEventPostUri = "sendEventPostUri",
        terminatePostUri = "terminatePostUri"
    });
}
```

then running 
```bash
curl -XGET 'http://localhost:7071/api/HttpTriggerCSharp1' -I

# > HTTP/1.1 202 Accepted
# > Transfer-Encoding: chunked
# > Content-Type: application/json; charset=utf-8
# > Server: Microsoft-HTTPAPI/2.0
# > Date: Fri, 30 Jun 2017 19:16:16 GMT

# {"id":"instanceId","statusQueryGetUri":"statusQueryGetUri","sendEventPostUri":"sendEventPostUri","terminatePostUri":"terminatePostUri"}
```

and 
```bash
curl -XGET 'https://app.azurewebsites.net/api/HttpTriggerCSharp1?code=<code>' -I


# > HTTP/1.1 202 Accepted
# > Cache-Control: no-cache
# > Pragma: no-cache
# > Content-Length: 135
# > Content-Type: application/json; charset=utf-8
# > Expires: -1
# > Server: Microsoft-IIS/8.0
# > X-AspNet-Version: 4.0.30319
# > X-Powered-By: ASP.NET
# > Date: Fri, 30 Jun 2017 19:16:45 GMT

# {"id":"instanceId","statusQueryGetUri":"statusQueryGetUri","sendEventPostUri":"sendEventPostUri","terminatePostUri":"terminatePostUri"}
```

**Comment by cgillum** [comment]
Ugh, sorry, I didn't properly analyze the problem.  What I was observing was that CreateResponse throws a 1st chance exception because XML serialization is failing. However, it turns out that the exception is handled internally and it switches to JSON serialization automatically.  If I would have continued execution, I would have seen that everything is actually working.  Including the `Accept: application/json` avoids the 1st chance exception.

It's still odd that it is trying to do XML serialization at all (and failing internally), but that's probably some odd behavior in Web API that doesn't have any user impact. Anyways, this is a non-issue.  Sorry about the noise.

**Comment by ahmelsayed** [comment]
yeah I thought defaulting to XML was a default behavior for webapi too. I initially had the cli explicitly change that to json, but then people asked to change it to match Azure behavior.
