### ISSUE TITLE
Running functions through CLI throws error compared to when ran in VS 2017

### ISSUE THREAD

**Issue by leolorenzoluis** [Azure/azure-functions-cli#173]
When running in VS 2017 15.3 Preview, I am able to run the function.

However, when I try to run the function through CLI after building the project, then I get an error.

A simple function method in my project is the following:

```
public static async Task RunAsync([BlobTrigger("profile-pictures/{name}")] CloudBlockBlob myBlob,  string name, TraceWriter log)
```

The function.json is:

```
{
  "bindings": [
    {
      "type": "blobTrigger",
      "path": "profile-pictures/{name}",
      "direction": "in",
      "name": "myBlob"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\Facebook.Functions.dll",
  "entryPoint": "Facebook.Functions.ResizeImage.RunAsync"
}
```

I get the following running `func run {FunctionName}`

>  mscorlib: Exception while executing function: Functions.ResizeImage. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'myBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.

**Comment by lindydonna** [comment]
You need to pass a container and blob name to func run, via the `-c` flag.
