### ISSUE TITLE
ScriptFile + NuGet Autofac dependency

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-functions-cli#175]
I've created a Functions project which is set-up as a web project with the functions executable as 'start external program' as per @lindydonna 's instructions. So far so good, everything works. In the project I'm referencing a DLL from another project, also works fine. 

Now I wanted to implement Autofac to do some dependency injection magic. So I added a NuGet reference to that project and created a ServiceLocator class for implementation. Now when I run my function, it fails stating it cannot find the Autofac ServiceLocator constructor. Very strange. Is there anything else I need to do in order to get these dependencies working? I checked the bin folder which holds all of the required DLLs.

For repro, get my code from https://github.com/jsiegmund/bots-domoticz. It currently also fails on a similar problem loading the Newtonsoft Json package.

**Comment by lindydonna** [comment]
I think this isn't currently possible, since we don't support DI. @fabiocav could you provide more info?

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1665
