### ISSUE TITLE
403 Forbidden Errors When Accessing Via Port Forwarding

### ISSUE THREAD

**Issue by jordanyaker** [Azure/azure-functions-cli#177]
As a temporary workaround until #13 is complete, I have setup a Vagrant box with Windows and Node.js installed on it.  From within the box, the hosted function works perfectly fine.  

In order to ease the pain of debugging, I have enabled port-forwarding on 7071 and 5858. 
 When attempting to access the function externally via the forwarded ports I am receiving a 403 error (see below).

     ~  curl -X POST -d "" http://localhost:7071/api/elements/order
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
    <HTML><HEAD><TITLE>Forbidden</TITLE>
    <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
    <BODY><h2>Forbidden URL</h2>
    <hr><p>HTTP Error 403. The request URL is forbidden.</p>
    </BODY></HTML>

Any thoughts?

**Comment by SteveALee** [comment]
You don't say what the destination host and port are for the forwarding? The CLI local server is hardcoded to use localhost (127.0.0.1). May be it checks the source of the request too?

I dont supposed the Functions' Proxy option is available locally but might be worth trying.

**Comment by jordanyaker** [comment]
Vagrant port forwarding binds to all ports unless otherwise specified (I don't specify).  This means that it is bound to localhost as well.  I've tested this by shutting down the host and trying the same call again; it returns a connection refused when `func host start` isn't running.

I was thinking it checks the source of the request, but if I specify `--cors *`  shouldn't that mitigate that?

**Comment by lindydonna** [comment]
Related to #174.

**Comment by jordanyaker** [comment]
@lindydonna I was actually trying to work around #174 as well.  Vagrant allows binding to all interfaces including 127.0.0.1.  By all accounts, this _should_ work.  I'm just not sure what element within the code is throwing the 403.

**Comment by lindydonna** [comment]
@jordanyaker I believe it's because the port is not exposed at all. @ahmelsayed can explain in more detail.

**Comment by jordanyaker** [comment]
@lindydonna @ahmelsayed if the port wasn't exposed, I would think that I would be getting an empty error like the example below (when the CLI isn't running) instead of a 403:

    curl -X POST -d "" http://localhost:7071/api/elements/order
    curl: (52) Empty reply from server
