### ISSUE TITLE
How to provide named parameters for "func run"?

### ISSUE THREAD

**Issue by eirikb** [Azure/azure-functions-cli#181]
I have bindings based on parameters, e.g., a "documentDB" with an id `"id": "{customer}"`, how can I provide a test-customer when using `func run my-function`?

Currently I run host, and use a script like this:
```bash
#!/usr/bin/env bash
touch ./index.js
sleep 1s
curl -s http://localhost:7071/api/my-function?customer=my-customer
```

**Comment by lindydonna** [comment]
Use -c to provide content. See https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#run-functions-locally

**Comment by eirikb** [comment]
Thank you for the answer @lindydonna .

I think the naming "Inline content" had me thinking it wasn't related to parameters.

**Comment by eirikb** [comment]
@lindydonna, this should probably be a separate issue, but the `touch index.js` in my script ensures that the function is reloaded, is there any way to do this from `func`?
E.g., if I require a script, say _api.js_ from _index.js_, and make changes to _api.js_ the function won't reload until I touch _index.js_ - at least not if  _api.js_ is stored in parent folder.

**Comment by lindydonna** [comment]
@eirikb Thanks for the feedback about "-c". We should probably use something like "function input" instead of "content".

To reload your supporting files, you can specify the root folder in `watchDirectories` in host.json: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

**Comment by eirikb** [comment]
@lindydonna Thanks again! 

In regards to `-c`, it could also be that users want to pass in both querystring and body with the same name, e.g., `http://localhost:7071/api/my-function?customer=my-customer -X POST -d '{"customer":"xyz"}'` - a bit of a corner-case I guess, and only relevant for HttpTriggers.

**Comment by lindydonna** [comment]
@eirikb Yeah, in that case we'd like folks to use cURL or Postman. We don't support all HTTP verbs, and we don't want to wrap curl.
