### ISSUE TITLE
"func host start" throws "Error: Cannot find module 'C:\Users\La�la B\AppData\Local\Azure.Functions.Cli\1.0.0-beta.100\edge\double_edge.js'"

### ISSUE THREAD

**Issue by ghost** [Azure/azure-functions-cli#182]
The folder name where the tools are installed is is "C:\Users\La**ï**la B\AppData\Local\Azure.Functions.Cli" and because of an encoding error somewhere it fails to correctly resolve the file name.

Kind regards,

**Comment by laila-digicreate** [comment]
More details:
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by lindydonna** [comment]
This looks like an issue with our dependency, Edge.js. We're eventually going to remove this issue, but in the meantime you should install in a different folder. You can download a zipfile manually from the URL specified here: https://aka.ms/functions-cli or download from the releases page: https://github.com/Azure/azure-functions-cli/releases
