### ISSUE TITLE
List All Deployed Functions

### ISSUE THREAD

**Issue by MarkTiedemann** [Azure/azure-functions-cli#187]
Using the CLI, I can retrieve all deployed function apps (`func azure functionapp list`). However, I cannot retrieve all deployed functions.

I noticed that there's an (undocumented) REST API which I can use at the following endpoint:

```http
https://management.azure.com:443/subscriptions/<subscription>/resourceGroups/<resourceGroup>/providers/Microsoft.Web/sites/<functionApp>/functions?api-version=<apiVersion>
```

So should I use that endpoint with [my own scripts](https://github.com/MarkTiedemann/list-azure-functions)? Are there plans to create a `func azure function list` command? Are there any best pratices related to this case that I am missing?

**Comment by ahmelsayed** [comment]
how about a `func azure functionapp list-functions <appName>`

**Comment by MarkTiedemann** [comment]
Yeah, sure. :) That makes sense since a function belongs to a function app.

PS: Same could be done for function slots and proxies.

**Comment by ahmelsayed** [comment]
https://github.com/Azure/azure-functions-cli/pull/190

I still need to add a test and clean up the code a bit. I'll be out for a couple of weeks, but should have a new release once I'm back in with these changes.

**Comment by MarkTiedemann** [comment]
Does this command also list the functions in different slots?

I remember I had to make a different API call when I tried to get those functions as well.
