### ISSUE TITLE
Automatically insert values for CLI version and script host version

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-cli#2]
_From @lindydonna on December 21, 2016 21:25_

_Copied from original issue: Azure/azure-webjobs-sdk-script#1070_

**Comment by lindydonna** [comment]
@ahmelsayed Is this already done?  The CLI seems to be printing the right host string.

**Comment by ahmelsayed** [comment]
Closing this as we need to update the version manually to match the milestone.

**Comment by lindydonna** [comment]
For script host, do we pull the version automatically?

**Comment by ahmelsayed** [comment]
You mean the value displayed in the help for the runtime version? Yes that comes from the runtime assembly itself.

**Comment by lindydonna** [comment]
Ah perfect!
