### ISSUE TITLE
[CLI] running local CLI with https?

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-functions-cli#20]
In a previous version of the CLI we could run using https. I've been trying to find which switch to use to get the CLI running in HTTP but haven't found it. Primary reason is that I wanted to try processing an OAuth response from SharePoint Online and that only accepts https endpoints. 

I've also ventured into securing the port with a certificate using netsh, but haven't got that to work (yet). 

In general, I think the documentation on the exact CLI parameters could use some work :)

**Comment by ahmelsayed** [comment]
I yanked out the https support a while ago, to refactor it but never added it again.
I'll look into adding it with beta.10 hopefully. Sorry about that.

**Comment by jsiegmund** [comment]
No problem. Any idea whether it should work with some netsh goodness, or is that going to be a dead end?

**Comment by ahmelsayed** [comment]
I'm afraid it'll be a dead end. you can setup the urlacl and sslcert manually through netsh, but [this](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L74) needs to bind to https uri.
I'll talk with @lindydonna  and see how soon we can get beta.10 out and it should be there.

**Comment by jsiegmund** [comment]
Right, ok! In the meantime I can proceed using an Azure instance and fiddling around with stuff there, but it would be very nice to have https back again for proper debugging :)

**Comment by ahmelsayed** [comment]
the command will be `func host start --useHttps --port <whatever port you want>`
If you run it without specifying a different port from the default (7071) though, it'll complain about a port conflict. I'm not sure if I should change the default port for https? before I had default https be 6061 and http be 7071.

**Comment by explorer14** [comment]
Hello! 

I tried passing those arguments to debug Azure functions locally on https but when I run the function from Visual Studio, I get this error, "host is taking longer than expected to start". Any ideas why this might be happening? Am I missing something really obscure and as yet undocumented?

![image](https://user-images.githubusercontent.com/1242932/31188798-094761c4-a92e-11e7-8864-bbdf516addc9.png)

Please let me know if you need anything  else to help with this.

Much appreciated
Aman
