### ISSUE TITLE
Is it possible to deploy a function app as a class library with only the dll, host.json and function.json?

### ISSUE THREAD

**Issue by ShayanZafar** [Azure/azure-functions-cli#200]
I am using the azure functionapp publish command and it is publishing my function along with the source code. we want to maintain the sourcecode locally and only deploy DLLs for running the function. How can i achieve this goal?

**Comment by ahmelsayed** [comment]
you'd need to use VS publishing for that. the CLI isn't smart enough to tell what should be published and what shouldn't. VS has the csproj and more knowledge about your project to publish the needed files only.
