### ISSUE TITLE
How Do I Output to BlobStorage Using Binding Syntax?

### ISSUE THREAD

**Issue by ssfcultra** [Azure/azure-functions-cli#201]
I have tried using the following two syntaxes to bind to BlobStorage and neither are working, though they did in the older style using function.json:

`[Blob("Merging/{QuickFindSBTopicTrigger}.txt", Connection = "AzureWebJobsStorage")]IBinder binder`
and 
`IBinder binder`

This is the code that uses it:
```
using (var outputBlob = binder.Bind<TextWriter>(
                new BlobAttribute(blobPath, FileAccess.Write)))
            {
                outputBlob.WriteLine($"Number to Union From: {string.Join(",", myQueueItem.NumberToUnionFrom)}");
                outputBlob.WriteLine($"Number to Union To: {string.Join(",", myQueueItem.NumberToUnionTo)}");
                outputBlob.WriteLine($"Output of Merge: {string.Join(",", myQueueItem.Output)}");
                outputBlob.WriteLine();
                outputBlob.WriteLine($"Runtime: {performance.Runtime.ToString()}");

                // create Sha512 Hash
                var sha = new SHA512CryptoServiceProvider();
                // This is one implementation of the abstract class SHA512.
                var result = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(blobPath + myQueueItem.NumberToUnionFrom + myQueueItem.NumberToUnionTo + myQueueItem.Output));
                outputBlob.WriteLine($"Hash of Inputs, Output and Runtime: {BitConverter.ToString(result).Replace("-", "")}");
            }


```

I just can't make either one write to BlobStorage.

Thoughts?

**Comment by lindydonna** [comment]
Here's documentation on how to use imperative bindings in Azure Functions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#binding-at-runtime-via-imperative-bindings

**Comment by ssfcultra** [comment]
Thanks @lindydonna! This bit solved my issues:

using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host.Bindings.Runtime;

public static async Task Run(string input, Binder binder)
{
    var attributes = new Attribute[]
    {    
        new BlobAttribute("samples-output/path"),
        new StorageAccountAttribute("MyStorageAccount")
    };

    using (var writer = await binder.BindAsync<TextWriter>(attributes))
    {
        writer.Write("Hello World!");
    }
}

**Comment by tamsps** [comment]
@ssfcultra Where to write these code lines? in .csx file (like run.csx) or inside of a azure function? Thanks

**Comment by tamsps** [comment]
@ssfcultra Also, I have a Azure Function
`[FunctionName("FunctionServiceBus")]
        public static void Run([ServiceBusTrigger("queue1", AccessRights.Manage, Connection = "AZServiceBusConn")]string myQueueItem, TraceWriter log)
        {
            log.Info($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
        }`

How can I load **queue1** (Service Bus Queue Name) and **AZServiceBusConn** (Service Bus connection string) at initialize (dynamic at run time). After these data were loaded then I let launch Azure Function trigger with new data. Many thanks
