### ISSUE TITLE
Enable .zip file deployment

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-cli#203]
For cases where Git-based deployment is too heavyweight, it would be nice to have the option of deploying using a .zip file or some other compressed package. 

`az functionapp deployment source config --name $functionapp --resource-group myResourceGroup --source-url --type zip`

**Comment by lindydonna** [comment]
Already supported via `func azure functionapp publish <FunctionAppName>`

**Comment by ggailey777** [comment]
@lindydonna can you provide an example of the command using a .zip file?

**Comment by ggailey777** [comment]
Sorry this was opened in the wrong repo. The ask was about Azure CLI.

**Comment by lindydonna** [comment]
Got it. We are thinking of wrapping the Functions CLI commands in the az CLI. We're also investigating ways to make deployment easier in the az CLI for both web apps and functions.
