### ISSUE TITLE
Binding to TableStorage for Output

### ISSUE THREAD

**Issue by ssfcultra** [Azure/azure-functions-cli#204]
I am running into and issue that used to work with function.json but no longer works with Web Jobs bindings. When I try to write to TableStorage with the following binding:

`[Table("Chapter01", Connection = "AzureWebJobsStorage")] IAsyncCollector<MergePerformance> outputTable`

Any thoughts? I definitely have the value AzureWebJobsStorage in my local.settings.json file. And this value used to be parsed automatically for me when I was using function.json but it appears it isn't doing so when I have started using WebJobs bindings.

Any thoughts?

**Comment by lindydonna** [comment]
Can you paste the contents of local.settings.json, eliding connection strings?

**Comment by ssfcultra** [comment]
Good morning Donna, 
The contents of my local.settings.json file is the vanilla values downloaded from Azure. I don't have them on my mobile but will add them once I get to work.

**Comment by anthonychu** [comment]
If the local.settings.json file was from the zip downloaded from Azure, there's a bug where the `Values` property is improperly named `Value`.

The fix is in this PR but it hasn't been looked at: https://github.com/projectkudu/kudu/pull/2500

**Comment by ssfcultra** [comment]
Thanks for the response @anthonychu , but that's not the problem. I downloaded the local.settings.json file through the CLI using: az func functionapp get-app-settings algorithmsfunctions.

Here are my settings, @lindydonna ...

```
{
  "IsEncrypted": true,
  "Values": {
    "AzureWebJobsDashboard": "<REMOVED BY SSFCULTRA>",
    "AzureWebJobsStorage": "<REMOVED BY SSFCULTRA>",
    "FUNCTIONS_EXTENSION_VERSION": "<REMOVED BY SSFCULTRA>",
    "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING": "<REMOVED BY SSFCULTRA>",
    "WEBSITE_CONTENTSHARE": "<REMOVED BY SSFCULTRA>",
    "WEBSITE_NODE_DEFAULT_VERSION": "<REMOVED BY SSFCULTRA>",
    "PERFORMANCETESTING_EXTENSION_VERSION": "<REMOVED BY SSFCULTRA>",
    "VSTS_PERF_TEST_CONFIG": "<REMOVED BY SSFCULTRA>",
    "AzureWebJobsSecretStorageType": "<REMOVED BY SSFCULTRA>",
    "AzureWebJobsServiceBus": "<REMOVED BY SSFCULTRA>"
  },
  "ConnectionStrings": {
    "AzureWebJobsServiceBus": "<REMOVED BY SSFCULTRA>"
  }
}
```

**Comment by ahmelsayed** [comment]
can you share your func.exe version, along with the content of function.json, which will be in the output of your project build. 
Also, are the values that have been redacted by you above actually encrypted or are they in plain text? I ask because the `IsEncrypted` flag is set to true

**Comment by ssfcultra** [comment]
@ahmelsayed Thanks for your response.

func.exe version: 1.0.0-beta.94
Function Runtime Version: 1.0.10826.0

The values are indeed encrypted. They came from the CLI using: az func functionapp get-app-settings algorithmsfunctions (name of my functions app)

function.json:
```
{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "AzureWebJobsServiceBus",
      "topicName": "algorithmsmerge",
      "subscriptionName": "QuickFind",
      "access": "manage",
      "direction": "in",
      "name": "myQueueItem"
    },
    {
      "type": "table",
      "tableName": "Chapter01",
      "connection": "AzureWebJobsStorage",
      "direction": "out",
      "name": "outputTable"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\AlgorithmsFunctions.dll",
  "entryPoint": "AlgorithmsFunctions.Chapter01.QuickFindSBTopicTrigger.Run"
}
```

**Comment by ahmelsayed** [comment]
hmm, can you try updating the CLI? the current version is 

```
Azure Functions Core Tools (1.0.0-beta.100)
Function Runtime Version: 1.0.11015.0
```

If you are getting it from npm, then the name changed there from `azure-functions-cli` to `azure-functions-core-tools` to reduce confusion with `azure-cli`. 
If you're getting it through Visual Studio, try deleting everything in this folder `C:\Users\<user>\AppData\Local\Azure.Functions.Cli` and restarting all instances of VS.

**Comment by ssfcultra** [comment]
Thanks @ahmelsayed! After updating to the latest version of the tools everything is working!
