### ISSUE TITLE
DocumentDB app.config redirects need to be updated

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-cli#206]
If anyone tries to use `DocumentClient` as a parameter type, it'll break. We're referencing 1.13.0 of DocDB, yet the redirect is going to 1.11.0:

https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/packages.config#L51
https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/App.config#L94

**Comment by lindydonna** [comment]
CC @ahmelsayed
