### ISSUE TITLE
Why must the CLI be installed globally?

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#21]
The first line in the readme says 

> This package only currently works on Windows and must be installed globally.

Why is that? I always install all dependencies locally, especially as I have npm scripts using the CLI.

It seems to work fine, though as usual you need to specify the path as usual, ie ```node_modules\.bin\func```

**Comment by ahmelsayed** [comment]
It should work locally as locally as well. **must** is a strong word, I probably meant ought to or should, at least that's how I test it, but I'll update the wording.
