### ISSUE TITLE
"fetch-app-settings" throws an error : "Unable to find function project root" 

### ISSUE THREAD

**Issue by praseetht** [Azure/azure-functions-cli#210]
When I tried the following command
`func azure functionapp fetch-app-settings <func-app-name>` I got the following error

`App Settings:`
`Loading AzureWebJobsDashboard = *****`
`Unable to find function project root. Expecting to have host.json in function project root.`

I am logged into Azure via `func azure login` and I am able to see the `<func-app-name>` in `func azure functionapp list`.
Also I verified that `host.json` exists in Azure Function Site root via **App Service Editor**

_Azure Functions Core Tools (1.0.1)_

**Comment by ahmelsayed** [comment]
the error is referring to the local directory where you're running `func azure functionapp fetch-app-settings <func-app-name>`

The cli is expecting that command to run in a function app directory. That is basically a local directory that has `host.json`. 
There is #51 which is tracking adding an option to download your function app, but for now, you can do that from the portal as shown below, then extract that zip into some directory and run from there. 

![2017-08-16_10-22-43](https://user-images.githubusercontent.com/645740/29376273-e15348aa-826c-11e7-8955-43aed6c72db0.gif)

**Comment by praseetht** [comment]
Thanks @ahmelsayed. I was under the impression that this command will fetch the setting from the function-app hosted in azure.

**Comment by ahmelsayed** [comment]
it does, but it needs to be within the context of a function app project locally. All that command does is issue a `POST` to `https://management.azure.com/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Web/sites/<appName>/config/appsettings/list?api-version=2016-08-01`

This returns the list of app settings defined in Azure, then it writes them to `local.settings.json` file (which can either be encrypted of plain text up to you). So it needs to be within a function app project. It's an artificial check, but if you're not running that from inside a function app project, then you are probably doing something I didn't expect, what are you trying to do exactly?

**Comment by praseetht** [comment]
Ahh..my bad.. got it  :thumbsup:
