### ISSUE TITLE
FSharp.Core

### ISSUE THREAD

**Issue by davidtme** [Azure/azure-functions-cli#216]
I’m having trouble getting a 3rd party package working in the cli and I think it’s because the version of fsharp.core shipped with cli is quite an old version (4.4.0.0)

_The 3rd party package is Suave.io but I have created the same problem with my own library class_

I think what is happen is:

My function is loaded and uses the fsharp.core that I have added via nuget:

```'func.exe' (CLR v4.0.30319: func.exe): Loaded 'C:\Users\xxx\FunctionApp\bin\Debug\net461\bin\FSharp.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.```

Then fsharp.core is re-loaded from the GAC as the because the bindingRedirect in func.exe.config

```'func.exe' (CLR v4.0.30319: func.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.4.0.0__b03f5f7f11d50a3a\FSharp.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.```

Which results in allsorts of missing functions errors
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Function1 ---> System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpFunc`2<HttpContext,Microsoft.FSharp.Control.FSharpAsync`1<Microsoft.FSharp.Core.FSharpOption`1<HttpContext>>> Suave.Successful.OK(System.String)'. at FunctionApp.Run@17.Invoke(Unit unitVar) at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object[] arguments) at async 
```

As a quite hack I try editing [App.config](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/App.config#L42) to 4.4.1.0 and everthing started to work

_I have seen that there is an [issues with binding redirect support](https://github.com/Azure/azure-webjobs-sdk-script/issues/992#issuecomment-298624059) but I can't get the "fix" code to work because I think f# is already loaded._

My code

```F#
module FunctionApp

open System.Net
open System.Net.Http
open System.Threading.Tasks
open Microsoft.Azure.WebJobs
open Microsoft.Azure.WebJobs.Extensions.Http
open Microsoft.Azure.WebJobs.Host

type Holder() =
    [<FunctionName("Function1")>]
    static member Run([<HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)>]req : HttpRequestMessage) =
        async {
            let b = Some "" // This is ok
            let a = Suave.Successful.OK "" // This fails 
            return req.CreateResponse(HttpStatusCode.OK, "OK");
        } |> Async.StartAsTask
```

**Comment by lindydonna** [comment]
This is a limitation of the Functions runtime, that you have to use the same versions as we deploy on Azure (because we run your code in the same process as the functions host). Please follow this issue for a fix to the underlying issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/1319
