### ISSUE TITLE
What version am I running?

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#219]
It's rather hard to tell what version I'm running and if it's the latest

The npm package is the latest available and is marked as 1.0.1. Yet the usage screen (for func --version) says 1.0.0-beta.100 (runtime version 1.0.11015.0)

Plus this https://github.com/Azure/azure-functions-cli/issues/130#issuecomment-323912772 says the latest is 1.0.2, at least for VS.

The release process isn't document in the README but I'm wonder if it's gone a bit squiffy?

**Comment by SteveALee** [comment]
Apologies, I confused myself by having `func` also globally installed. Now uninstalled. The version in the usage matches the npm module at 1.0.1

However why not 1.02? Have the versions diverged?

**Comment by lindydonna** [comment]
The npm package has now been updated. You can find out if it's the latest by going to npm or running an npm command (not sure the exact syntax)

**Comment by SteveALee** [comment]
Thanks. The thing I can't do is check if the npm package is up to date with the manage version :)
