### ISSUE TITLE
Verb options are missing from the usage info

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#22]
The usage info that is printed by the CLI does not explain any of the options.

for example [blog post](https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/) says we should use:

> func run .\HttpTrigger-JS\ -c "{\"name\": \"Debugging!\"}" --debug

but the ```-c``` and ```--debug`` switches are not described anywhere

BTW the way is ```func run``` identical to ```func function run```?

**Comment by ahmelsayed** [comment]
yep I need to add that.
To answer your question though, run takes `--file\-f` and `--content\-c` to send to the function being run.
`--debug` is function dependent, if javascript, it sets launch.json, if C#, it launches VS debugger.

**Comment by SteveALee** [comment]
Thanks

FYI I did see some strings in one of the branches on the old repo. Perhaps from before the verbs were restructured?

**Comment by ahmelsayed** [comment]
The help strings themselves are [already in the code](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L47-L81) I just need to print them in the help output.
