### ISSUE TITLE
Cursor position out of range

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-cli#220]
This is particularly prominent on macOS, but repros on Windows as well.

When creating a function (`func new`), if the height buffer size is small (e.g. smaller than the template or language list), the calculation to get the value that is used to set the cursor top may yield a negative value, leading to the following error:

```
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -<value>.
```
#### Workaround
The current workaround is to ensure a large enough console buffer/size.

**Comment by ahmelsayed** [comment]
should be fixed in 2300901a103206a85cec4caa944986aa0c83c011 
the experience is a bit different between windows and unix consoles as it seems that `Console.CursorTop` behaves differently for some reason
