### ISSUE TITLE
Host file watch needs to include shared modules as well as function entrypoint files

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#221]
The host is pretty good at watching for changes in the function and json files but it fails to spot changes in shared modules.

For example, I've quite a few javascript files in a `_modules` folder (underscore indicates private, not a Function). When these change the function app is not reloaded. It should be.

I suggest also watching `functionApp/**/*.js` would probably be good enough. Possibly `functionApp/*.json` too

**Comment by SteveALee** [comment]
I have a [workaround using nodemon](http://azureserverless.com/2017/08/22/watching-typescript-files-while-developing-local-functions/) to restart the host

**Comment by lindydonna** [comment]
If you want to watch other directories, you should add them to watchDirectories: https://github.com/Azure/Azure-Functions/issues/454

**Comment by SteveALee** [comment]
@lindydonna Azure/Azure-Functions#454 doesn't seem at all relevent?

**Comment by lindydonna** [comment]
Oops, copy-paste error. You can customize watchDirectories in host.json: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

**Comment by SteveALee** [comment]
I hadn't grocked webjob options would be available with core tools. Cool. Thanks for the headsup. I'll explore.
