### ISSUE TITLE
Enable CORS on .NET Core branch

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#222]

**Comment by fabiocav** [comment]
Fixed in 8c31384

**Comment by lindydonna** [comment]
I thought it was fixed, but just confirmed that it doesn't work for me. I tried building the latest as well as getting the latest from npm.

**Comment by fabiocav** [comment]
Please test with the latest bits. Verified working, but please reopen if you still have problems.

**Comment by lindydonna** [comment]
@fabiocav Confirmed it's working with the latest bits. Thanks for the help!

**Comment by MisinformedDNA** [comment]
I am using Sdk.Functions 1.0.13. Here is my `local.settings.json`:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": "UseDevelopmentStorage=true"
  },
  "Host": {
    "CORS": "*",
    "LocalHttpPort": 7071
  }
}
```

The pre-flight succeeds:
![image](https://user-images.githubusercontent.com/1784452/43047803-c44d6adc-8da2-11e8-91ad-f4a94ca57724.png)

But the actual call fails:
![image](https://user-images.githubusercontent.com/1784452/43047816-e4ed868c-8da2-11e8-80d6-c600d901f997.png)

Chrome give additional output in the console:
![image](https://user-images.githubusercontent.com/1784452/43047841-44c8eb64-8da3-11e8-8cff-534e0c0b4480.png)

What am I doing wrong?
