### ISSUE TITLE
Can we have --debug option for host verb?

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#23]
Currently it appears debug mode can only be entered when directly running a function with data (like the portal Test feature)

I want to launch the server and then prod it with HTTP triggers. This locally simulates how HTTPTriggers are used on Azure.

The workaround is to run a dummy 'null' function with ```--debug``` to start the server and then as the server [usually] stays running use browser/postman etc. to invoke the function.

We also need a description of what debug does. It obviously updates the VS Code launch.json and then starts the server listening. But what else? See #22

**Comment by SteveALee** [comment]
does is open a port for the debugger then we can Ah, I see. I don't suppose you'll need to support mixed language functions for a while :)

Yes, my first thought was I understand there is a plan to reduce the fragmentation of languages over debuggers. 

Sigh, why can't they all use the same debug tools/ports/apis etc?

**Comment by SteveALee** [comment]
This would also allow us to launch the host and debugger without having to press a key.

**Comment by lindydonna** [comment]
@ahmelsayed The vscode C# debugger won't work until we port to .NET Core, unfortunately.

**Comment by lindydonna** [comment]
I like `--debug vs` and `--debug vscode`.
