### ISSUE TITLE
Create a new function: no languages to pick from are available 

### ISSUE THREAD

**Issue by bgc3data** [Azure/azure-functions-cli#234]
When typing either "func new" or "func function create" I get the correct prompt "Select a language" but there are no lists of languages to pick from. Trying to use the down arrow and select an invisible one (if exists) causes the following error: "Index was outside the bounds of the array"

For reference, I currently have 30 azure functions in the same app.

**Comment by ahmelsayed** [comment]
@bgc3data there was an issue yesterday with the templates endpoint that should be fixed now. Can you give it another try now?

_some details: the cli just queries [this feed ](https://github.com/Azure/azure-functions-cli/blob/a920cf62f22c43a519c052042b4ed5aa14684266/src/Azure.Functions.Cli/Common/TemplatesManager.cs#L29) and displays whatever templates are there_

**Comment by bgc3data** [comment]
Yes that fixed it. Thanks for following up.
