### ISSUE TITLE
Func host start fails to run multiple javascript functions

### ISSUE THREAD

**Issue by nelak** [Azure/azure-functions-cli#254]
`func host start` fails to run multiple javascript functions:

I have this layout for my functions

* host.json
* function1
  * function.json
* function2
  * function.json

function.json:
```json
{
 "bindings": [
  {
   "name": "queue",
   "type": "queueTrigger",
   "direction": "in",
   "queueName": "queue-items",
   "connection": "AzureWebJobsDashboard"
  }
 ],
 "disabled": false,
 "_originalEntryPoint": false,
 "_originalScriptFile": "index.js",
 "scriptFile": "../.funcpack/index.js",
 "entryPoint": "function1"
}
```

The number of functions is identified correctly:
`[9/26/17 2:16:57 PM] Generating 2 job function(s)`

But I get the following error on my functions:
`Worker dc79521e-121e-42bc-b822-2aa03560ea04 uncaught exception:  Unable to determine function entry point. If multiple functions are exported, you must indicate the entry point, either by naming it
 'run' or 'index', or by naming it explicitly via the 'entryPoint' metadata property.`

The entry point is correctly defined as this is working in Azure, my guess is that metadata from the `function.json` is not flowing correctly to the worker process causing this issue.

**Comment by mamaso** [comment]
Thanks for the info @nelak! I'll give it a look - there may be some issues around relative script paths on different systems.

**Comment by nelak** [comment]
@mamaso I've been using funcpack locally and with Azure without issues for some time already.
I can see the two workers get started but it would seem that they fail to find the entry point. 
From what I see funcpack is generating a bundle that returns the entryPoints as properties of the module.exports, kinda:
```js 
{ 
function1: handler1, 
function2: handler2
}
``` 
My guess based on my what I could follow in 
is that https://github.com/Azure/azure-functions-nodejs-worker/blob/d65cc30fcbbc780bcf745e2f4606e9d4bdfc1325/src/WorkerChannel.ts#L64 may not be getting the proper metadata which would seem to make the functionLoader fail when trying to resolve the entry point here https://github.com/Azure/azure-functions-nodejs-worker/blob/d65cc30fcbbc780bcf745e2f4606e9d4bdfc1325/src/FunctionLoader.ts#L56
Sadly I'm uncertain on how to debug this end to end to verify the scenario as I'm currently doing all my work on WSL
Let me know if I can provide with more information

**Comment by nelak** [comment]
@mamaso I was able to get a debug environment running and found the issue inside the node worker. It's a subtle bug that may be triggered when using entry points.

After resolving the entry point the result always expects a function:
https://github.com/Azure/azure-functions-nodejs-worker/blob/d65cc30fcbbc780bcf745e2f4606e9d4bdfc1325/src/FunctionLoader.ts#L56
In this scenario the error message ends up being deceptive causing confusion because the entry point exists and it's resolved, but the failure is caused by the resolved entry point not being a function.

**Reproduce steps**
Configure a function for which the entry point doesn't return a function
e.g.: mistype `module.exports` and you'll end up with a valid entry point referencing an empty object

**Proposed Solution**
Improve the check and add a different message for when the entryPoint has been resolved but it is not a function

**Comment by mamaso** [comment]
@nelak great work and good suggestion!

You're welcome to contribute a PR if you like, otherwise I'll add that in.

In this particular scenario, is it a user error that the entry point is not a function, or an error in our tooling?

**Comment by nelak** [comment]
@mamaso It's probably a user error, either they may have mistyped the module.exports or it could be that they bound an object to the module.exports that'll get resolved by the entryPoint.
So you have two different scenarios one being not being able to resolve the entry point and the other one the result of the entry point not being a function itself.
What I'm thinking is to split the validation in two, only testing if(!f) in the getEntryPoint method and moving the isFunction validation outside to perform isFunction(!userFunction) throw "error message" to handle this two scenarios.
I'm currently looking at how to compile the worker so I can test with the CLI, test the results and I'll send a PR sometime tomorrow.  Just to check my understanding of how to test this, I'll have to webpack the results to get the nodeworker bundle and use that one with the CLI and it should work right?

**Comment by mamaso** [comment]
From the cli you can add arguments: `--workers node:path=<path-to-nodejsWorker.js>`, or you could set an environment variable `workers__node__path = <path>` (it's essentially using Microsoft.Extensions.Configuration)

You don't need to webpack for the bundle either - the build results in `dist` from `npm run build` should work as well.

**Comment by nelak** [comment]
Thanks for the reference, it helped me be able to test this a lot easier, still the toolchain is really hard to setup since you keep hitting some hardcoded paths.
PR is ready, let me know if you want me to modify anything there.

**Comment by mamaso** [comment]
closed in https://github.com/Azure/azure-functions-nodejs-worker/pull/44
