### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by buragc** [Azure/azure-functions-cli#256]
I am trying to install the cli on my mac using the following:

`npm i -g azure-functions-core-tools@core`

It is failing with the following message:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for azure-functions-core-tools@1.0.0-beta.100: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

**Comment by ahmelsayed** [comment]
/cc @mamaso 

can you make sure your node version >= 8.4.0? It looks like our package has that [dependency now ](https://github.com/Azure/azure-functions-cli/blob/f610028d0640ad7f71be4ce6ecc89e4a9c8cf9e4/src/Azure.Functions.Cli/npm/package.json#L28) and it's messing with npm version resolution for some reason. I think it's trying to give you the latest that supports your node engine version or something, but it's falling back to a pretty old version.

We will remove that restriction from the package

**Comment by ahmelsayed** [comment]
and the version you want is `2.0.1-beta.17`, not `1.0.0-beta.100` which is very old

**Comment by buragc** [comment]
@ahmelsayed I am running node v8.4.0. 

One thing I noticed is that if I install locally (without the -g flag) it resolves to the correct version `2.0.1-beta.17` but when -g flag is used, it falls back to v1.0.0-beta.100

I tried uninstalling this version from global packages with `npm uninstall -g azure-functions-core-tools` however, I get the same error described above. So it looks like I cannot uninstall or upgrade this package globally at the moment.

**Comment by ahmelsayed** [comment]
can you try

```bash
rm -rf /usr/local/lib/node_modules/azure-functions-core-tools # or where ever your global npm packages go

# then
sudo npm i -g azure-functions-core-tools@core --unsafe-perm
```
_[--unsafe-perm docs](https://docs.npmjs.com/misc/config#unsafe-perm)_

**Comment by ahmelsayed** [comment]
an alternative to --unsafe-perm (if you don't want to run install script as root) is to do
```bash
npm config --global set user $(whoami | id -u)
```

that should tell npm to run the install scripts as your UID instead of `nobody`, though this will affect any package you install with sudo.

**Comment by buragc** [comment]
Just to close the loop. The only thing that worked was the 
```
rm -rf /usr/local/lib/node_modules/azure-functions-core-tools # or where ever your global npm packages go

# then
sudo npm i -g azure-functions-core-tools@core --unsafe-perm
```

I was able to install with this.
