### ISSUE TITLE
Create VS Code launch.json during scaffolding of func init

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#26]
One customer got confused when they didn't see launch.json, as they had expected it to be created during initialization. The downside of creating the file is that VS Code debugging only works for JavaScript, so customers might be confused if they have other function types.

Expected behavior:
- Create launch.json with a default port (if it doesn't already exist)
- CLI should read launch.json if it exists and use that port. (This will allow for multiple ports on the same machine)

**Comment by SteveALee** [comment]
Now I'm confused as I'm sure one got created for my first function! I guessed was part of --debug option and remember wondering what would have happened if I had already had a launch.json. however it didn't happen when a scaffolded my 2nd function in same applies

Perhaps code offers to create one?

**Comment by SteveALee** [comment]
I was NOT imagining it :) - see https://github.com/Azure/azure-functions-cli/issues/22#issuecomment-271712075

**Comment by lindydonna** [comment]
Create launch.json with a default port. CLI should read launch.json if it exists and use that port. (This will allow for multiple ports on the same machine)

**Comment by SteveALee** [comment]
Need to make sure not to trample of any pre existing launch.json for VS code project

**Comment by lindydonna** [comment]
@SteveALee Good point, I updated the issue with that detail.

**Comment by SteveALee** [comment]
just read in the latest vs code release notes something that might interact wit this

> Automatically choosing debug environment
> Depending on the active file, VS Code can now automatically choose a debug environment instead of explicitly asking the user. For example, if a user has a JavaScript file active in an editor and wants to setup his launch.json, a launch.json for JavaScript is automatically generated.
