### ISSUE TITLE
func host start does not work on Linux on 2.0.1-beta.18

### ISSUE THREAD

**Issue by valorekhov** [Azure/azure-functions-cli#270]
running on linux
```bash
func host start
```
results in a message that ~/.azurefunctions/bin/workers/Node/dist/src/nodejsWorker.js module is missing.
Upon investigation, it appears that this is a case-sensitivity issue with the path as the ~/.azurefunctions/bin/workers/node folder does exist on the installation

the temporary fix is to create a symlink

```bash
ln -s ~/.azurefunctions/bin/workers/node ~/.azurefunctions/bin/workers/Node
```

**Comment by fabiocav** [comment]
Thank you for reporting this (and for the workaround!)

This has been fixed in https://github.com/Azure/azure-webjobs-sdk-script/pull/1923/commits/dc24339ae223bf9ca447cefdb28f225f3eface5a which will be included in the next update.

**Comment by fabiocav** [comment]
I've updated the list of[ known issues ](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Azure-Functions-runtime-2.0-known-issues) to cover this and included a link to your workaround.
