### ISSUE TITLE
Unhandled exceptions cause host to die

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#28]
If an exception is thrown and unhandled in the function then host window closes after a timeout.

Is this expected? Does the same happen on Azure - ie function app dies?

Should we always have a catch block at the top of our functions or is there another technique?

**Comment by lindydonna** [comment]
@fabiocav can answer this better than I can. The host does behave differently locally vs. running in Azure, but he can tell you the exact behavior.

**Comment by lindydonna** [comment]
@SteveALee Could you provide a repro?  I didn't see it with null ref.

**Comment by SteveALee** [comment]
@lindydonna I can't. It happened a couple of times but as I was getting to the min code the behaviour changed to printing a stack trace in red in the host window rather than closing it. I now can't get it to fail again now.
