### ISSUE TITLE
Cli: Run a function from a list of functions in a functionapp locally 

### ISSUE THREAD

**Issue by mz-rafiq** [Azure/azure-functions-cli#31]

**Comment by ahmelsayed** [comment]
Can you explain what you mean a bit more? Is this a feature request or something that's not working as you're expecting?

**Comment by mz-rafiq** [comment]
I have a function app with some function in it 
how can i run only one function instead of all function locally?

**Comment by mz-rafiq** [comment]
I have a function app with some functions in it
how can i run only one function instead of all functions locally?

**Comment by lindydonna** [comment]
Use `func run`. See https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli for a walkthrough

**Comment by mz-rafiq** [comment]
I've already try `func run <functionname>` but it's not working.

**Comment by SteveALee** [comment]
I can confirm it does usually work. 

One thought you did use ```func init```? I forget that sometimes for a new folder and then it doesn't work

You'd need to provide more info about your configuration for any one to help.

**Comment by mz-rafiq** [comment]
I have three time trigger functions
first function start every minute second every 2 minutes and third every 3 minutes.
when i run only the second function using CLI with `func run secondFunction` comand this is the out put: 

Listening on http://localhost:7071/
Hit CTRL-C to exit...
Reading host configuration file 'C:\dev\Azure Functions\New folder\host.json'
Host lock lease acquired by instance ID '000000000000000000000000B567BE4B'.
Generating 3 job function(s)
Starting Host (HostId=369676140f284042807825956a6e3a0c, Version=1.0.0.0, ProcessId=8444, Debug=True)
Found the following functions:
Host.Functions.firstFunction
Host.Functions.secondFunction
Host.Functions.thirdFunction

Executing 'Functions.secondFunction' (Reason='This function was programmatically called via the host APIs.', Id=8710a77f-434f-4580-a51c-65719866dcd6)
Function started (Id=8710a77f-434f-4580-a51c-65719866dcd6)
C# second function executed at: 1/19/2017 12:49:37 PM
Function completed (Success, Id=8710a77f-434f-4580-a51c-65719866dcd6)
Executed 'Functions.secondFunction' (Succeeded, Id=8710a77f-434f-4580-a51c-65719866dcd6)
Job host started
Executing 'Functions.firstFunction' (Reason='Timer fired at 2017-01-19T12:50:39.3050459+01:00', Id=ff39e5eb-16d2-4183-88f6-8f6166182edf)
Function started (Id=ff39e5eb-16d2-4183-88f6-8f6166182edf)
C# first function executed at: 1/19/2017 12:50:39 PM
Function completed (Success, Id=ff39e5eb-16d2-4183-88f6-8f6166182edf)
Executed 'Functions.firstFunction' (Succeeded, Id=ff39e5eb-16d2-4183-88f6-8f6166182edf)
Executing 'Functions.secondFunction' (Reason='Timer fired at 2017-01-19T12:50:39.3220597+01:00', Id=059506d5-c155-48b4-9be9-0e7cbc4515d5)
Function started (Id=059506d5-c155-48b4-9be9-0e7cbc4515d5)
C# second function executed at: 1/19/2017 12:50:39 PM
Function completed (Success, Id=059506d5-c155-48b4-9be9-0e7cbc4515d5)
Executed 'Functions.secondFunction' (Succeeded, Id=059506d5-c155-48b4-9be9-0e7cbc4515d5)
The next 5 occurrences of the schedule will be:
1/19/2017 12:51:00 PM
1/19/2017 12:54:00 PM
1/19/2017 12:57:00 PM
1/19/2017 1:00:00 PM
1/19/2017 1:03:00 PM

The next 5 occurrences of the schedule will be:
1/19/2017 12:51:00 PM
1/19/2017 12:52:00 PM
1/19/2017 12:53:00 PM
1/19/2017 12:54:00 PM
1/19/2017 12:55:00 PM

The next 5 occurrences of the schedule will be:
1/19/2017 12:52:00 PM
1/19/2017 12:54:00 PM
1/19/2017 12:56:00 PM
1/19/2017 12:58:00 PM
1/19/2017 1:00:00 PM

Executing 'Functions.firstFunction' (Reason='Timer fired at 2017-01-19T12:51:00.0036647+01:00', Id=6a837330-0451-47ca-b173-f4b07a310fe2)
Function started (Id=6a837330-0451-47ca-b173-f4b07a310fe2)
C# first function executed at: 1/19/2017 12:51:00 PM
Function completed (Success, Id=6a837330-0451-47ca-b173-f4b07a310fe2)
Executed 'Functions.firstFunction' (Succeeded, Id=6a837330-0451-47ca-b173-f4b07a310fe2)
Executing 'Functions.thirdFunction' (Reason='Timer fired at 2017-01-19T12:51:00.0166724+01:00', Id=380aef01-fe10-4c8c-93ae-d8f9324946a8)
Function started (Id=380aef01-fe10-4c8c-93ae-d8f9324946a8)
C# third function executed at: 1/19/2017 12:51:00 PM
Function completed (Success, Id=380aef01-fe10-4c8c-93ae-d8f9324946a8)
Executed 'Functions.thirdFunction' (Succeeded, Id=380aef01-fe10-4c8c-93ae-d8f9324946a8)
Executing 'Functions.firstFunction' (Reason='Timer fired at 2017-01-19T12:52:00.0010279+01:00', Id=027cd34c-1bcb-4e3b-bf26-1ee4cc93976a)
Function started (Id=027cd34c-1bcb-4e3b-bf26-1ee4cc93976a)
C# first function executed at: 1/19/2017 12:52:00 PM
Executing 'Functions.secondFunction' (Reason='Timer fired at 2017-01-19T12:52:00.0010279+01:00', Id=e2e02e0b-e376-42c5-9bde-b3ce6cf2143b)
Function started (Id=e2e02e0b-e376-42c5-9bde-b3ce6cf2143b)
C# second function executed at: 1/19/2017 12:52:00 PM
Function completed (Success, Id=e2e02e0b-e376-42c5-9bde-b3ce6cf2143b)
Executed 'Functions.secondFunction' (Succeeded, Id=e2e02e0b-e376-42c5-9bde-b3ce6cf2143b)
Function completed (Success, Id=027cd34c-1bcb-4e3b-bf26-1ee4cc93976a)
Executed 'Functions.firstFunction' (Succeeded, Id=027cd34c-1bcb-4e3b-bf26-1ee4cc93976a)
Executing 'Functions.firstFunction' (Reason='Timer fired at 2017-01-19T12:53:00.0009321+01:00', Id=9c478d57-f7e4-431c-85d1-2d5970290522)

And so on...
why firstFunction and secondFunction run?

**Comment by lindydonna** [comment]
@mz-rafiq This is a confusing behavior of `func run` that needs to be documented (I've added this note to this issue: https://github.com/Azure/Azure-Functions/issues/108).

When you do `func run functionName`, the CLI does two things: 1) starts the Functions Host (which will cause other triggers to fire, if applicable), and 2) invokes the entry point of `functionName`.

Thanks for raising this, this is something we should definitely clarify in both the docs and ideally the CLI help text. 

I'm closing this particular issue as it will be resolved with documentation.

**Comment by SteveALee** [comment]
It seems we need a list of all the differences between local and azure as you mentioned another diff recently.

For example on this case I guess in azure the host is run but sleeping till the timers trigger?

Out of interest when exactly do the timers start ticking in both cases?

**Comment by mz-rafiq** [comment]
`{
	"functions":["secondFunction"]
}
` in host.json resolved my problem

**Comment by lindydonna** [comment]
@mz-rafiq You can also disable the function you don't want to run, but I assumed you were looking for a solution that didn't involve changing the config.

@SteveALee In this case, the local and remote behave the same. When you're in the Azure Portal, the functions are running and triggering if the function is enabled. If the timer is defined as very far in the future (e.g. a timer that runs every day), then when you run in a dedicated plan, the Functions runtime is doing the scheduling. If you use a Consumption plan, the central listener will wake up the Function app when it needs to execute.

See https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#consumption-service-plan for more details.
