### ISSUE TITLE
Cannot install azure-functions-core-tools@core on Ubuntu Xenial (16.04)

### ISSUE THREAD

**Issue by anaelcarvalho** [Azure/azure-functions-cli#331]
Script fails installation (npm i -g azure-functions-core-tools/@core) with output below:

`anael@Straylight:~/azure/functions/demo$ sudo npm i -g azure-functions-core-tools@core
/usr/local/bin/func -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azfun -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azurefunctions -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js

> azure-functions-core-tools@2.0.1-beta.22 postinstall /usr/local/lib/node_modules/azure-functions-core-tools
> node lib/install.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/azure-functions-core-tools/bin'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@2.0.1-beta.22 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the azure-functions-core-tools@2.0.1-beta.22 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anael/.npm/_logs/2017-12-04T17_14_38_205Z-debug.log
`
Should mkdir run with '-p' in order to create the full path?

Thanks!

**Comment by agentelinux** [comment]
Hi,
try:
sudo npm install -g azure-functions-core-tools/@core --unsafe-perm=true --allow-root

**Comment by anaelcarvalho** [comment]
Looks like that worked, thanks!

**Comment by evictor** [comment]
Works on my OS X, except needed to omit `/@core`
