### ISSUE TITLE
Environment Variables in function.json broken

### ISSUE THREAD

**Issue by ansario** [Azure/azure-functions-cli#34]
Function.json:
```
{
  "bindings": [
    {
      "accessRights": "Listen",
      "connection": "connect-service-bus",
      "direction": "in",
      "name": "message",
      "subscriptionName": "%connect-service-bus-subscription%",
      "topicName": "%connect-service-bus-topic%",
      "type": "serviceBusTrigger"
    }
  ],
  "disabled": false
}
```

Appsettings.json

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "ConnectionStringRedacted",
    "AzureWebJobsDashboard": "ConnectionStringRedacted",
    "connect-service-bus": "ConnectionStringRedacted",
    "connect-service-bus-topic": "connect-service-bus-topic",
    "connect-service-bus-subscription": "connect-service-bus-subscription",
    "APPSETTING_documentDBEndpoint": "ConnectionStringRedacted",
    "APPSETTING_documentDBPrimaryKey": "ConnectionStringRedacted",
    "APPSETTING_documentDBCollection": "connectdb",
    "APPSETTING_documentDBName": "connectcollection",
    "APPSETTING_APPINSIGHTS_INSTRUMENTATION_KEY": "ConnectionStringRedacted",
    "APPSETTING_loggingEnabled": "true",
    "APPSETTING_telemetryEnabled": "true"
  }
}
```

Trying to run the function app using the Azure CLI for VS results in an error logged "A ScriptHost error has occured."

**Comment by kr00p** [comment]
How did you resolve this issue? We're running into the same problem, trying to configure output to Azure Notification Hub and we're unable to set `hubName` through the resource's Application Settings in Azure Portal. The `%variable%` inside function.json doesn't get resolved at all.

**Comment by ansario** [comment]
My question was specifically about using app settings locally with the Azure Function CLI. Could you post an anonymized version of your function.json?

**Comment by kr00p** [comment]
Our function.json:
```{
  "bindings": [
    {
      "name": "notificationModel",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "notification-queue",
      "connection": "SERVICEBUS_CONNECTION",
      "accessRights": "Manage"
    },
    {
      "type": "notificationHub",
      "name": "notification",
      "hubName": "%NOTIFICATIONHUB_NAME%",
      "connection": "NOTIFICATIONHUB_CONNECTION",
      "tagExpression": "{tag}",
      "enableTestSend": true,
      "direction": "out"
    }
  ],
  "disabled": false
}
```

In the resource's properties we have an app setting called `NOTIFICATIONHUB_NAME` (this doesn't work) and a connection string `NOTIFICATIONHUB_CONNECTION` (this one does). This is done according to the [official docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#resolving-app-settings).

**Comment by SteveALee** [comment]
The obvious difference is that %NOTIFICATIONHUB_NAME% has %s round it.

**Comment by kr00p** [comment]
...which is exactly how the [official docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#resolving-app-settings) describe it:

> App settings are resolved whenever a value is enclosed in percent signs, such as `%MyAppSetting%`. Note that the `connection` property of triggers and bindings is a special case and automatically resolves values as app settings.

**Comment by SteveALee** [comment]
But NOTIFICATIONHUB_CONNECTION doesn't? Seems inconsistent if both are defined same way in App settings and one works and the other doesn't. But I'm only making an observation from ignorance

**Comment by kr00p** [comment]
It does seem inconsistent, but it's described that way pretty clearly. One detail though: connection strings are defined in a separate section and are sometimes retrieved differently (e.g. in .NET apps).
