### ISSUE TITLE
VS Code debugger doesn't attach after first launch 

### ISSUE THREAD

**Issue by navzam** [Azure/azure-functions-cli#35]
## Description
Debugging a Function works fine on the first launch. On future launches, the debugger doesn't start listening until the Function has already run once. Is this expected behavior?

### Create the Function
```
mkdir DebugTest
cd DebugTest
func init
func new
```
Choose JavaScript --> Generic Webhook

### Debug the first time
Run the function:
```
func run .\GenericWebhookJS\ -c "{\"first\": \"Nafis\", \"last\": \"Zaman\"}" --debug
```
The host starts and outputs:
```
Job host started
Http Function GenericWebhookJS: http://localhost:7071/api/GenericWebhookJS
File change of type 'Changed' detected for 'C:\Users\nazam\Desktop\DebugTest\.vscode\launch.json'
Host configuration has changed. Signaling restart.
Stopping Host
Job host stopped
Reading host configuration file 'C:\Users\nazam\Desktop\DebugTest\host.json'
Generating 1 job function(s)
Starting Host (HostId=404a4c263e864fabaafbfdae0af967aa, Version=1.0.0.0, ProcessId=16628, Debug=False)
Found the following functions:
Host.Functions.GenericWebhookJS

Job host started
Debugger listening on [::]:5858
```
In VS Code, attach the debugger. In the original terminal, press any key to continue. The Function executes and debugs as expected.

### Debug the second time
In VS Code, disconnect the debugger. Kill the Functions host from before. Run the same command to run the Function:
```
func run .\GenericWebhookJS\ -c "{\"first\": \"Nafis\", \"last\": \"Zaman\"}" --debug
```
The host starts and outputs:
```
Job host started
Http Function GenericWebhookJS: http://localhost:7071/api/GenericWebhookJS
```
**Note that the debugger did not start listening.** In VS Code, attaching the debugger fails. In the original terminal, press any key to continue. The Function executes (no debugging). The host outputs:
```
Executing 'Functions.GenericWebhookJS' (Reason='This function was programmatically called via the host APIs.', Id=0bdba42c-6e47-4b80-8833-744e066efa23)
Function started (Id=0bdba42c-6e47-4b80-8833-744e066efa23)
Debugger listening on [::]:5858
Webhook was triggered!
Function completed (Success, Id=0bdba42c-6e47-4b80-8833-744e066efa23)
Executed 'Functions.GenericWebhookJS' (Succeeded, Id=0bdba42c-6e47-4b80-8833-744e066efa23)
```
NOW the debugger is listening.

**Comment by lindydonna** [comment]
Looks like a bug, I changed the subject line to be specific to VS Code

**Comment by ahmelsayed** [comment]
This is because of Edge\runtime behavior. Edge doesn't start listening on the debug port until it's invoked in some way, and the host doesn't invoke any of Edge's APIs until a JavaScript Function is invoked. 
@fabiocav @mathewc Do you see any concern adding a dummy Edge call in the cli to initialize Edge?

```csharp
var func = Edge.Func("return function (data, callback) { callback(null, 'Node.js welcomes ' + data); }");
await func("init");
```
