### ISSUE TITLE
Starting today windows defender recognises x64 func.exe as a Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by rzio** [Azure/azure-functions-cli#364]
I've re-downloaded the latest x64 runtime 1.0.7 to verify. when trying to unzip it, it's blocked by windows defender.

**Comment by ahmelsayed** [comment]
It looks like x64 builds weren't being signed. 9ed5a77ff491ce0126433e9929d85ae500bb9e6a should take care of that. 1.0.8-x64.zip should be signed.
