### ISSUE TITLE
Provide option to publish appsettings as part of function app publish

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#41]
Related to content publish (#8)

**Comment by ahmelsayed** [comment]
```
publish             Publish the current directory contents to an Azure Function App. Locally deleted files are not removed from destination.
    <FunctionAppName>             Function App name
    --publish-local-settings [-i] Updates App Settings for the function app in Azure during deployment.
    --overwrite-settings [-y]     Only to be used in conjunction with -i. Overwrites AppSettings in Azure with local value if different. Default is prompt.
```

**Comment by lindydonna** [comment]
@ahmelsayed Nice!

**Comment by gunzip** [comment]
thank you for your work and sorry for re-open this, but probably the AppSettings publishing
part ("functionapp publish") should mirror  "functionapp fetch-app-settings" behavior, where we get ConnectionStrings imported as well (aside AppSettings). 

At the moment is not possible to push (publish) local ConnectionStrings configuration to the remote Azure functionapp (w/local.settings.json).

**Comment by SteveALee** [comment]
slightly off topic but I'm sure I saw an `-o --only-publish-settings` option listed in the usage but now it has vanished.

Did I imagine it?

**Comment by SteveALee** [comment]
@gunzip is this covered by #214 ?

**Comment by gunzip** [comment]
@SteveALee no, it's a different request. 

#214 is about *importing* ConnectionStrings from local.settings.json to the local (dev) environment when running 'func host' locally.

this one is about *exporting* ConnestionStrings from local.settings.json to the remote (running in Azure cloud) functionapp ConnectionStrings settings (nothing to do with process.env).

they are related anyway, but cover different parts of sources.

**Comment by ahmelsayed** [comment]
@gunzip would you mind opening another issue for publishing connection strings? I agree it's missing now and should be there.

**Comment by gunzip** [comment]
done #215

**Comment by jboarman** [comment]
@SteveALee, I was looking for exactly that feature and searched the google and came across this "undocumented feature" referenced in this commit by our dear friend @ahmelsayed:  https://github.com/Azure/azure-functions-cli/commit/434b16dc90bad0deed9c24da0ff22447557ca190

This worked for me.  However, it still required additional local dependencies beyond the `local.settings.json` file, which is disappointing as we might have an admin that needs to maintain configuration separate from the code, and the only dependency in that scenario should be the settings themselves.

As a result, I've created a new issue to request this extended functionality.  Check out #339 and add your comments.

**Comment by SteveALee** [comment]
@jboarman hey, thanks for that info - I'll try it!
