### ISSUE TITLE
Provide a better error message when there's an invalid connection string for AzureWebJobsStorage 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-cli#5]
_From @lindydonna on December 3, 2016 1:40_

#### Repro steps

1. Create a Azure Function project in Visual Studio

2. Use an invalid connection string for AzureWebJobsStorage in appsettings.json

#### Expected behavior

Error message saying that the connection string for `AzureWebJobsStorage` is invalid

#### Actual behavior

In a loop, you get the following:

```Reading host configuration file 'C:\CDriveCode\Visual Studio Projects\FunctionApp2\host.json'
ScriptHost initialization failed
```

_Copied from original issue: Azure/azure-webjobs-sdk-script#1024_

**Comment by ahmelsayed** [comment]
_From @lindydonna on December 21, 2016 2:2_

@soninaren Would this be handled by your fix in the SDK?

**Comment by ahmelsayed** [comment]
_From @soninaren on December 21, 2016 2:17_

No, this is not handled by the SDK fix. Actually we are getting this error. 
`Settings must be of the form "name=value".`
But it is swallowed here 
https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L503

**Comment by stephlocke** [comment]
+1 for getting errors passed through! 

After upgrading to beta.9 today I can't get scripthosts to initialise and it would be helpful to have more transparent messaging!

**Comment by ahmelsayed** [comment]
I feel like this is more of https://github.com/Azure/azure-functions-cli/issues/4#issuecomment-270431383 Or do you know you had that error because of an invalid connection string?

to unblock you, do you mind looking at `%temp%\LogFiles\Application\Functions\Host\*.log` and share the error you see there? You might need to delete that file first, then run the host again just to make sure you're not looking at an older error.

**Comment by stephlocke** [comment]
Saw #4 after ending up on this. Connection wasn't invalid but realised as I was typing this that maybe my local storage emulator hadn't been turned on after windows restarted itself earlier due to updates. D'oh! So turned it on & yay fixed.

I was getting the issue because my connection strings were pointing at local dev storage but local dev storage was unavailable. The log files hadn't updated at all today as it seemed to be erroring on host initialization, pre-logging for the host.

**Comment by lindydonna** [comment]
@soninaren is this related to your other fixes?

**Comment by soninaren** [comment]
The fixes i put in only check if connection string is present, we need to add another check to verify if the connection string format is valid.

**Comment by ahmelsayed** [comment]
This has been fixed already.
