### ISSUE TITLE
400 error reported when calling func azure functionapp create

### ISSUE THREAD

**Issue by iain-peddie-tessella** [Azure/azure-functions-cli#50]
## Repro steps

I have a resource group for which I am an owner; I am also a co-admin on the subscription the resource group is in. I have installed the functions-cli.

I am now calling the following commands from a bash shell on my local machine:

func azure login
func azure account set $sub
func azure functionapp create --resource-group $rg --name $app_name --subscription $sub --plan $plan_id --location $location

I have set variables up correctly as far as I can tell. These variables are:
$rg : contains the resource group name
$sub: contains the relevant subscritpion - my account has access to both
$app_name : contains the name of the function app that I want to create
$plan_id : contans the name of a created app service plan in the same resource group.

The commands fail at the third step.

## Expected behavior

Provide a description of the expected behavior.
I expect the function app compoment to be created, or failing that an error message that explains why something has failed so that I can fix the issue if the input is incorrect. For example: "Error: you have used an app service plan ID , but we need the app service name".

## Actual behavior

I get an error message that doesn't help me understand what has gone wrong:

   ```at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WebJobs.Script.Cli.Arm.ArmManager.<CreateFunctionsStorageAccountAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<EnsureAStorageAccountAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Arm.ArmManager.<CreateFunctionAppAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Actions.AzureActions.CreateFunctionAppAction.<RunAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

Provide a description of the actual behavior observed.

## Known workarounds

Create via the portal and use an ARM template - in which case why have the setup option here at all?

## Related information

I have been creating this using bash scripting using git-bash on a windows 10 development machine. I have used a similar approach with Azure CLI 2 to create a storage account and a app service plan.

I am running version 1.0.0-beta.9

Running fiddler doesn't show any 400 reposnes on my machine - which suggests that the 400 error is happening remotely and then being sent back in a 200 response?

**Comment by ahmelsayed** [comment]
Hi @iain-peddie-tessella,
Thank you very much for the detailed bug report, I wish more people were that through :)

This is however same as #27. Create action doesn't work right now, and I have removed it as the plan is to keep all azure management scenarios (create, update, delete, etc) for the [Azure CLI]() while keeping this tool for dev scenarios only to reduce duplication and confusion. There are obvious blurred lines between dev and ops scenarios, but hopefully we can find the right compromises. 

I'll close this issue, but feel free to let us know if you disagree and we can discuss it further.

**Comment by iain-peddie-tessella** [comment]
Hi AhmedIn that case, can I make two points:Firstly, it would be sensible to adjust the documentation. I presume the correct approach is to use ARM templates via the normal command line tool?Secondly, The npm module indicates to submit bug reports to the web tools github page, not here. So there is now a duplicate of this issue on their setup. I think it would be good to get that documentation updated to - it will just save everyone some time.CheersIainIain PeddieMathematical Developer Email: iain.peddie@tessella.comSkype: iain.peddie.tessellaTel: +44 (0)1438 749886 Richmond House, Walkern Road, Stevenage, SG1 3QPTessella is part of the Altran Group - www.tessella.com Please consider the environment and do not print this e-mail unless you really need to.  This message is commercial in confidence and may be privileged. It is intended for the addressee only. Access to this message by anyone else is unauthorised and strictly prohibited. If you have received this message in error, please inform the sender immediately. Please note that messages sent or received by the Tessella e-mail system may be monitored and stored in an information retrieval system. Tessella is Registered in England No. 1466429 -----Ahmed ElSayed <notifications@github.com> wrote: -----To: Azure/azure-functions-cli <azure-functions-cli@noreply.github.com>From: Ahmed ElSayed <notifications@github.com>Date: 02/06/2017 10:44AMCc: Iain Peddie <iain.peddie@tessella.com>, Mention <mention@noreply.github.com>Subject: Re: [Azure/azure-functions-cli] 400 error reported when calling func azure functionapp create (#50)Hi @iain-peddie-tessella,
Thank you very much for the detailed bug report, I wish more people were that through :)
This is however same as #27. Create action doesn't work right now, and I have removed it as the plan is to keep all azure management scenarios (create, update, delete, etc) for the Azure CLI while keeping this tool for dev scenarios only to reduce duplication and confusion. There are obvious blurred lines between dev and ops scenarios, but hopefully we can find the right compromises.
I'll close this issue, but feel free to let us know if you disagree and we can discuss it further.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




This message is commercial in confidence and may be privileged.  It is intended for the addressee(s) only.  Access to this message by anyone else is unauthorized and strictly prohibited.  If you have received this message in error, please inform the sender immediately.  Please note that messages sent or received by the Tessella e-mail system may be monitored and stored in an information retrieval system.
