### ISSUE TITLE
Publish should display an interactive warning if host.json is not found in current directory

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#53]
You can accidentally publish a function to a Function App if you happen to be in the function folder. 

Should do the following:
- Look for host.json in the current folder
- If not found, display the following message: `Warning: host.json not found in current folder. Proceed with publishing the current directory to Azure Function App $name?`
- Add `--ignore` command line argument (`-i` for short) to not prompt

**Comment by ahmelsayed** [comment]
Alternatively we can throw an error if host.json is not found and have the flag override it. 
We can also travel up the directory tree to find a host.json and then use that directory, throw error if not, use current directory if --ignore is passed (how about `--ignoreHostJsonNotFound` instead. I think `--ignore` might be too generic?)

What do you think?

**Comment by lindydonna** [comment]
Agreed on both counts. I like traversing up to find host.json, that's a nicer customer experience.
