### ISSUE TITLE
Improve error message for Timer trigger when AzureWebJobsStorage is not set

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-cli#6]
_From @TonyAbell on November 27, 2016 19:51_

Steps
--

* func init
* func new  
(Select timer template, and give it a name of timer)
* func run timer

Error
--
> A ScriptHost error has occurred
> Stopping Host
> Unable to retrieve functions list: No MediaTypeFormatter is available to read an object of type 'FunctionEnvelope[]' from content with media type 'text/plain'.

Language 
--
I have tried this on the following languages, with the same results for each one.
* C#
* F#
* JS 

 @ahmelsayed 

_Copied from original issue: Azure/azure-webjobs-sdk-script#993_

**Comment by ahmelsayed** [comment]
_From @lindydonna on December 15, 2016 1:49_

@TonyAbell Did you have a value for AzureWebJobsStorage in appsettings.json?  This is likely a poor error message that needs to be improved.

**Comment by ahmelsayed** [comment]
_From @desinole on December 15, 2016 16:5_

I had the same issue with a brand new TimerTrigger project. Setting the "AzureWebJobsStorage" value to "UseDevelopmentStorage=true" in the appsettings.json file fixed it

**Comment by ahmelsayed** [comment]
_From @lindydonna on December 21, 2016 22:2_

@ahmelsayed's proposal: 
1) Test to see if local storage emulator works ok for common scenarios
2) Inject this value (and print a warning to the console) if AzureWebJobsStorage is null

**Comment by ahmelsayed** [comment]
_From @lindydonna on December 21, 2016 22:3_

Error message issue will be fixed with https://github.com/Azure/azure-webjobs-sdk-script/issues/1069

**Comment by lima02** [comment]
@ahmelsayed I have tried the following and still having issues. Can you pls shed some light?
**appsettings.json:**
`{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": ""
  }
}
`
I get this...
Reading host configuration file 'C:\src\SC-Contracts\host.json'
Listening on http://localhost:7071/
Hit CTRL-C to exit...
**ScriptHost initialization failed**

**Comment by lindydonna** [comment]
You should use a connection string for AzureWebJobsStorage. Local development storage isn't guaranteed to work correctly.

Here's a video walkthrough that shows how to get the setting: https://regularitguy.com/2017/01/11/the-coolness-of-visual-studio-azure-functions-tools/

**Comment by ahmelsayed** [comment]
Fixed.

**Comment by atrauzzi** [comment]
@lindydonna Is there any way to have this setting pulled from here?

![image](https://cloud.githubusercontent.com/assets/115199/23948345/9ecfb2ec-0950-11e7-8714-08f85ec2e057.png)

The reason I'm asking is because I don't have anything environment specific in my project files.  My resource templates configure all the settings I need in the Azure App Service instance.

**Comment by mkamonster** [comment]
I think these settings can be retrieved via **ConfigurationManager.AppSettings["SettingName"]**. Did you try this?

**Comment by atrauzzi** [comment]
Well, this is the webjobs/functions framework that requires these settings.  So it won't be up to me to pull them.  But it appears to be working to just have them set in the application settings as a string.

@lindydonna - This might be another one of those grey areas of requirements/functionality I seem to be good at finding.  Functions apps do have some prerequisites, so when I want to automate my deployments, I have to know that certain infrastructure and associated credentials have to exist and be made available to the app service instance.

**Comment by lindydonna** [comment]
You can use `func azure functionapp fetch-app-settings` to pull down the settings to your local machine.

Using an ARM template to automate Function App creation is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code
