### ISSUE TITLE
appsettings.json content should be available using ConfigurationManager.AppSettings

### ISSUE THREAD

**Issue by iain-peddie-tessella** [Azure/azure-functions-cli#64]
##Summary

I would like to be able to have my function read some content from AppSettings when developing locally. This works on the Azure function, but when running locally, the AppSettings are empty

## Configuration

I have an application setting I would like to run. As it happens, it is a connection string. I know that the connection string is correctly stored in appsettings.json, because another function in the same function app can connect to the storage folder. 

So I have something similar to the following code in appsettings.json

```json
{
"IsEncrypted" : false,
"Values" : {
  "AzureWebJobsStorage" : "",
  "AzureWebJobsDashboard" : "",
  "AzureWebJobsMyConnectionString" : "<something secret>"
}
}
```

Then in my function I have the following code:

```c#
  var appSettings = ConfigurationManager.AppSettings;
  if (appSettings.Count == 0)
  {
       log.Info("AppSettings is empty");
  }

  foreach(var key in appSettings.AllKeys)
  {
       log.Info($"Key : {key} Value : {appSettings[key]}");
   }    
```

(log is the TraceWriter instance).

## Observed behaviour

Using *Functions CLI*, I get the output : 

```
AppSettings is empty
```
 However, when I push to Azure, I get the full listing of all the application settings available in the Application Settings sub-blade in the App Service Settings blade under the Function App. A few lines of the log output *in azure* are:

```
2017-02-09T17:49:36.134 Key : FUNCTIONS_EXTENSION_VERSION Value : ~1
2017-02-09T17:49:36.134 Key : ScmType Value : LocalGit
2017-02-09T17:49:36.134 Key : WEBSITE_AUTH_ENABLED Value : False
2017-02-09T17:49:36.134 Key : REMOTEDEBUGGINGVERSION Value : 11.0.611103.400

```

This includes the connection strings AzureWebJobsDashboard and so on - which I know are registering for the functions CLI  because I can read and write data to the storage account configured in the appsettings.json (which is the standard local emulation developer account)

## Exptected Behaviour

I expect that when using the CLI tools, I can query the AppSettings using ConfigurationManager. This will make the local environment consistent with the Azure environment. 

If a different mechanism is supposed to be used to set local application settings than `ConfigurationManager.AppSettings` in Fucntions, it would be nice for this to be documented. 

## Details

I am using Azure Functions CLI version (1.0.0-beta9) with Function Runtime version 1.0.0.0.

**Comment by ahmelsayed** [comment]
this was added in 1.0.0-beta.10 (which latter became 1.0.0-beta.91, it's due to a bug in VS version comparison where 10 < 9, but 91 > 9) 
Please upgrade and try again

**Comment by ahmelsayed** [comment]
Ref: #33
