### ISSUE TITLE
OPTIONS Method: Does not seem to work with Azure-Functions-CLI

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-functions-cli#66]
Hello,
      When I attempt to run a function that implements the OPTIONS method it works fine on regular Azure, but the Azure Functions CLI when using:
`func run myFunction`

All I get back are 400 messages.

The functions.json:
```
    {
      "disabled":false,
      "bindings":[
        {
          "name": "req",
          "type": "httpTrigger",
          "direction": "in",
          "authLevel": "anonymous",
          "methods": [ "OPTIONS" ],
          "route": "1.0/myFunction"
        },
        {
          "name": "res",
          "type": "http",
          "direction": "out"
        }
      ]
    }
```

The code:
  ```
  'use strict';
    
    module.exports = function(context, req){
        var shared = require('../auth-shared-libraries');
        var cors_url = shared.getCORSUrl(context);
        context.res = {
            status: 200,
            headers: {
                "Access-Control-Allow-Credentials" : "true",
                "Access-Control-Allow-Origin" : cors_url,
                "Access-Control-Allow-Methods" : "POST, OPTIONS",
                "Access-Control-Allow-Headers" : "Content-Type, Set-Cookie",
                "Access-Control-Max-Age" : "86400",
                "Vary" : "Accept-Encoding, Origin",
                "Content-Type" : "application/json"
            },
            body : JSON.stringify(req)
        };
        context.done();
    }

```

The Request:
```
    OPTIONS /api/1.0/myFunction HTTP/1.1
    Host: localhost:7071
    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Access-Control-Request-Method: POST
    Origin: http://localhost:9000
    Connection: close
```

The Response:
```
    HTTP/1.1 400 Bad Request
    Content-Type: application/json; charset=utf-8
    Server: Microsoft-HTTPAPI/2.0
    Date: Tue, 14 Feb 2017 01:28:12 GMT
    Connection: close
    Content-Length: 64
    
    {"Message":"The origin 'http://localhost:9000' is not allowed."}
```

**Comment by SteveALee** [comment]
I wonder if this is as there is a different frontend server? 

I had problems with CORS and Preflight. Never resolved

**Comment by securityvoid** [comment]
@SteveALee The error certainly implies there is something else looking at CORS and rejecting based on the value. Beyond that, I really don't know. I can tell you it is definitely creating headaches for me since this makes local dev impossible, and deployment takes ~10 minutes which REALLY slows down the development cycle.

**Comment by lindydonna** [comment]
@securityvoid We'll investigate. Just curious, why does deployment take 10 minutes?  It should be much faster than that.

**Comment by securityvoid** [comment]
@lindydonna I'm using nodejs which the way it handles dependencies requires a lot of installs. Since the [Azure file system is so slow, it typically makes request to NodeJS apps that have more than 4-5 dependencies be extremely slow.](https://github.com/Azure/azure-webjobs-sdk-script/issues/298) 

[To get around the performance issue at run-time I've created a custom deploy script that takes all the dependencies and converts them into a single minified file, which is then used by my main index.js. ](https://github.com/securityvoid/.deploy)While that script takes 30 seconds to run locally, it takes 10 minutes to run on the amazingly fast Azure storage. This makes the run-time performance much higher, but takes awhile to deploy.

Even before I used a custom deploy script the deploy time used to be 5+ minutes on a refresh of NPM's. The initial npm install deploy was, and still is about an hour.

**Comment by securityvoid** [comment]
However, since everything is minified, this also makes it more difficult to debug when its on Azure; and even more important for me to be able to do development locally before pushing it out to Azure.

**Comment by lindydonna** [comment]
@securityvoid Thanks for sharing the details, that makes a lot of sense. You might be interested in a prototype that @christopheranderson has been working on, that [does Webpack on dependencies](https://github.com/christopheranderson/azure-functions-pack). However, it uses a feature that hasn't been released to Azure yet. 

Ironically, due to an oversight where currently the CLI uses slightly newer runtime bits than Azure (will be fixed in the next release), you can try out his tool locally. I realize it might not be that useful until the CORS issue is resolved, of course!

**Comment by SteveALee** [comment]
@securityvoid 10 mins! Yeouch. I've found it slow but that is crazy.

I find npm really slow on windows, even running scripts. I was beginning to wonder if NTFS is just slow for some reason.

One solution would be to locally build your node modules, zip and ftp it to Azure. A real hack though.

Time to try yarn? install -g on the target and upload the local lock file before running it.

**Comment by lindydonna** [comment]
@SteveALee FYI there's now a publish command in the CLI. It's not complete (it won't remove deleted files), but it'll make the workflow a little nicer. Have you tried @christopheranderson's webpack approach?

**Comment by securityvoid** [comment]
@lindydonna We use auto-deploy from source-control. As a result I'm pretty sure that his solution would require us to return to source-control the webpacked version of the node modules for it to deploy. Returning dependencies to source-control is generally not viewed as a best practice.

The deploy script I put together is completely workable as long as we can do most of our development locally. 10 minutes for a deploy is not ideal, but its also not a big deal for a release. Its just not productive for active development.

@SteveALee I run windows 10 and I have no trouble with the speed of npm. Granted I'm also running with 16GB of memory and a 1TB SSD :-). I've also optimized some of the NPM commands, e.g. disabling the progress bar (Yes, it actually helps for some weird reason), and increasing the time period that packages are cached.

**Comment by SteveALee** [comment]
@lindydonna nope - but he recently mentioned something. I guess it bundles up stuff?

@securityvoid You could always uses another repo just for the deployment or FTP as a fina step in a CICD pipeline. But if you are using these Apps pull deployment form your main repo that will all be extra work. :(

/OT I've an i7 Surface pro 4 so similar spec but npm often slow to start scripts. I do tend to run from Msys Bash shell. Oh and nvm windows. I should try stripping it all down, including paths etc,. Thanks for comments.

**Comment by abhinav-jain09** [comment]
did we get it resolved this issue?
