### ISSUE TITLE
Running func settings add AzureWebJobsStorage UseDevelopmentStorage=true clears any ConnectionStrings out of appSettings.json

### ISSUE THREAD

**Issue by mkamonster** [Azure/azure-functions-cli#67]
When I run
```
func settings add AzureWebJobsStorage UseDevelopmentStorage=true
```

The connectionstrings I have in appsettings.json get's cleared out.

**Comment by ahmelsayed** [comment]
I'm not able to repro this with the 91 release. Which version are you using?

**Comment by ahmelsayed** [comment]
I'm gonna close this as no repro as I can't repro it. Please feel free to reopen if you're still seeing this.
