### ISSUE TITLE
Content-Type: Not passed in the Request Headers

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-functions-cli#68]
Hello,
      It does not appear that "Content-Type" is handled so that it shows up under:
`req.headers`

This appears to be true for both Azure Functions Cli and the actual Azure deployments. (Not sure if this means I should open this issue elsewhere).

Interesting this data does appear to be within:
`context.bindingData`

I can parse this out, but can someone please explain why Content-Type wouldn't be passed with the rest of the headers?

I've got a form-data object that I need to parse to extract a file upload. There are packages that will do this automatically (e.g. busboy), if I pass in the Content-Type/boundary.

It seems weird to me that this wouldn't be included in the details.

**Comment by ahmelsayed** [comment]
I do think this should be moved to the runtime repo https://github.com/Azure/azure-webjobs-sdk-script

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1314
