### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-cli#7]
_From @lindydonna on November 4, 2016 18:19_

Create an automated build for the CLI and ideally run some CLI tests.

_Copied from original issue: Azure/azure-webjobs-sdk-script#877_

**Comment by ahmelsayed** [comment]
_From @lindydonna on November 4, 2016 18:19_

This can be done after code complete, obviously

**Comment by cyplo** [comment]
There is an appveyor build linked in the README but it seems that it does not triggered on push to master. What would be a plan here to getting this complete ? Thank you !

**Comment by lindydonna** [comment]
@ahmelsayed started working on the automated builds, he can tell us the status

**Comment by ahmelsayed** [comment]
I'm waiting on https://github.com/Azure/azure-webjobs-sdk-script/pull/1083 to get merged as currently the build is failing. Once that is done I'll setup automatic builds on appveyor. Sorry for moving slow on this

**Comment by ahmelsayed** [comment]
this is done
