### ISSUE TITLE
Debugging f#/fsharp function in VS2015

### ISSUE THREAD

**Issue by davidtme** [Azure/azure-functions-cli#73]
I have a blank c# function which works:

```C#
using System;

public static void Run(string input)
{
}
```

Which runs and I can debug:

![image](https://cloud.githubusercontent.com/assets/1804141/23022484/fe96b490-f448-11e6-9922-e70b0d50ed0c.png)

If I change it to an F# file:

```F#
open System

let Run(input: string) =
    ignore()
```

it runs but I get an error meaning I can't debug:

![image](https://cloud.githubusercontent.com/assets/1804141/23022530/39f16d8c-f449-11e6-8e54-f57d03e29d9f.png)

**Comment by lindydonna** [comment]
This issue was moved to Azure/Azure-Functions#183
