### ISSUE TITLE
the command  func azure functionapp create no longer works

### ISSUE THREAD

**Issue by Zazcallabah** [Azure/azure-functions-cli#75]
When I updated to Azure Functions Cli (1.0.0-beta.91) the scripts we use for automated setup and deploy of new functions apps stopped working.

I see this commit https://github.com/Azure/azure-functions-cli/commit/5221e9035b7c5d0f29df12cdffc76e38eaa3d4cb removed something that definitely looks like it was what we were using, and I wonder why it was removed, or perhaps more importantly, what method we should use to create function apps from the command line going forward.

**Comment by ahmelsayed** [comment]
Reasoning is explained in #50 I probably should've added that to the commit message.
But to summarize, the method will be through [azure cli](https://github.com/Azure/azure-cli) while keeping this to dev scenarios to reduce people getting confused by "why there are many CLIs for azure stuff"
We will probably rename this project to something other than cli down the line as well, though it's just a repo rename. Shouldn't affect anything else.

**Comment by ahmelsayed** [comment]
I'll close this issue

**Comment by Zazcallabah** [comment]
The azure cli is a) dependent on python, which is a dealbreaker for us. It is also, b) documented nowhere how to use it to create function apps.
