### ISSUE TITLE
Allow specifying a custom port in appsettings.json

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#79]
(edited with new design)

If the port is specified in appsettings but also command line, command line takes precedence. Should update the help text in port command line option to make it clear.

Add a new object "Host" where we can put multiple settings:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "AzureWebJobsDashboard": ""
  },
  "Host": {
    "LocalHttpPort": 7071
  }
}
```

**Comment by ahmelsayed** [comment]
I don't know of any http server that does this, mainly for the reason that you have to know the port it's running on to interact with it. If you know that this will always be on 7071, then you don't need to worry about it. If the CLI changes the default port without explicit action, then you'd need to check which port it picked everytime. There is already a `-p\--port` arg to change the port.

**Comment by ahmelsayed** [comment]
removing milestone to triage again.

**Comment by lindydonna** [comment]
@ahmelsayed Good point, but we do print out the port once we've chosen it. I guess I was thinking of web project setup in VS where it picks a port (I think randomly). 

Maybe a better option is to allow customers to specify a port in appsettings.json.

**Comment by lindydonna** [comment]
If the port is specified in appsettings but also command line, command line takes precedence.

Use a setting at the top level, peer to "IsEncrypted"

>  "LocalHttpPort": 7071,
