### ISSUE TITLE
Deploy Azure Function via Kudu or FTP

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-cli#8]
Command line: `func azure functionapp publish`

_From @mikezks on October 28, 2016 10:54_

[Feature] request

The [npm website](https://www.npmjs.com/package/azure-functions-cli) shows how to deploy a local Azure Function to Azure Portal.

At least for beginners who do not have a CI scenario with github configured, it would be easier to deploy via Kudu or FTP.

It would be helpful to include such a tutorial in the npm website (maybe with [kudusync](https://www.npmjs.com/package/kudusync)?).

_Copied from original issue: Azure/azure-webjobs-sdk-script#846_

**Comment by cmatskas** [comment]
@ahmelsayed there are a few websites that show you how to do this with PowerShell (xplat) and the Kudu REST API.

**Comment by lindydonna** [comment]
Should zip the entire function app and publish. Can investigate individual function publish later.
