### ISSUE TITLE
New Azure Functions CLI 1.0.0-beta.92 is failing to load Nuget.Frameworks, Version=3.4.3.0

### ISSUE THREAD

**Issue by mkamonster** [Azure/azure-functions-cli#81]
Hi,

I just updated the Azure Functions CLI to 1.0.0-beta.92 and I'm no longer able to start any Azure Function.

Even when starting a new Azure Functions project, the Azure Functions host starts with the following error.

`Host lock lease acquired by instance ID '000000000000000000000000E3BC87C8'.
Error processing package references.

Could not load file or assembly 'NuGet.Frameworks, Version=3.4.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Function compilation error`

**Comment by mkamonster** [comment]
It seems the beta.92 is missing some NuGet files. I copied them over from the beta.91 and now it seems to work as expected.

![image](https://cloud.githubusercontent.com/assets/1837517/23648294/530edec8-031a-11e7-9990-3542f485107e.png)

Missing files:
- NuGet.Frameworks.dll
- NuGet.LibraryModel.dll
- NuGet.Versioning.dll

**Comment by BenAffleckIsBatman** [comment]
+1

**Comment by apulliam** [comment]
+1

**Comment by ahmelsayed** [comment]
fixed in 16fd572dfa02664cdc0989195bb4576a619f3163

Please close and reload Visual Studio or update your npm package to get beta.93
sorry about that.
