### ISSUE TITLE
func run <FunctionName> only returns “Response Status Code : NotFound” when methods property set in function.json

### ISSUE THREAD

**Issue by jonathanfishbein1** [Azure/azure-functions-cli#82]
See following stackoverflow

http://stackoverflow.com/questions/42378288/azure-function-cli-func-run-functionname-only-returns-response-status-code

**Comment by lindydonna** [comment]
This is by design, func run only calls POST. We didn't want to reimplement CURL, so we're going to print a warning to this effect. See https://github.com/Azure/azure-functions-cli/issues/85
