### ISSUE TITLE
Could not load file or assembly 'NuGet.Frameworks, Version=3.4.3.0,

### ISSUE THREAD

**Issue by Dafnafrank** [Azure/azure-functions-cli#83]
I have created a new project with an Azure function on VS 2015.
Added no new code of mine.
When I am trying to run it, I get the following error message:

"Could not load file or assembly 'NuGet.Frameworks, Version=3.4.3.0,"

Any idea how I fix this...?
I tried uninstalling nuget package from Tools\Extensions
didn't work

I noticed that under: C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
I have many folders, one of them is : C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\NuGet.Frameworks with 3 folders: "3.5.0", "3.5.0-beta", "3.5.0-beta2-1484"

Maybe this is the reason it cannot find version 3.4.3....?

Would appreciate your assistance. Thanks

**Comment by ahmelsayed** [comment]
fixed in 16fd572dfa02664cdc0989195bb4576a619f3163

Please close and reload Visual Studio or update your npm package to get beta.93
