### ISSUE TITLE
Environment-specific settings for development

### ISSUE THREAD

**Issue by juunas11** [Azure/azure-functions-cli#84]
Is it somehow possible for us to have settings that are specific to the development environment? Something akin to the client secrets of ASP.NET Core? Currently I use environment variables for this, and that works, but is it possible to do this in a more project-specific way?

And if not, could that be on the roadmap in the future? :)

**Comment by lindydonna** [comment]
Are you familiar with appsettings.json?  That's how you can provide settings specific to your functions project. We don't currently have a way to easily share settings across functions projects.

**Comment by juunas11** [comment]
I am aware of that, but that would be checked in to source control by default :) In this case I need to set a client secret that gives the function access to an API. But this is not something I want in the version control system.

Do you think a good option would be to add appsettings.json to .gitignore and set settings specific to my development environment there?

**Comment by lindydonna** [comment]
Yes, you should definitely put appsettings.json in .gitignore. `func init` actually creates a .gitignore for you with this specified.

**Comment by lindydonna** [comment]
Closing issue.

**Comment by juunas11** [comment]
Thanks for the swift response!
