### ISSUE TITLE
Rename Azure Functions CLI to Azure Functions Core Tools

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#92]
- Use the name change feature in npm
- Update strings in code

**Comment by ahmelsayed** [comment]
this is done https://www.npmjs.com/package/azure-functions-core-tools

**Comment by patrickdenglerhobbisoft** [comment]
failure log (note, no debug log was created)


From: Patrick Dengler (CW) 
Sent: Tuesday, September 5, 2017 10:40 AM
To: 'mamaso@microsoft.com' <mamaso@microsoft.com>
Subject: npm i -g azure-functions-core-tools failure log

C:\WINDOWS\system32>npm i -g azure-functions-core-tools 
npm WARN engine chalk@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-styles@3.2.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine supports-color@4.4.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
C:\Users\pdengler\AppData\Roaming\npm\node_modules\azure-functions-core-tools\node_modules\chalk\index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\pdengler\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "azure-functions-core-tools"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! azure-functions-core-tools@1.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@1.0.2 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the azure-functions-core-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls azure-functions-core-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by ahmelsayed** [comment]
``
npm ERR! node v0.12.2
```

upgrade to some more recent version of node. Current LTS node is 6.x

**Comment by lee212** [comment]
I was experiencing a related issue while installing `azure-functions-core-tools`, and just wanted to share my workaround.

The error message that I had is:
```
$ sudo npm install -g azure-functions-core-tools@core
/usr/local/bin/func -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azfun -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azurefunctions -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js

> azure-functions-core-tools@2.0.1-beta.22 postinstall /usr/local/lib/node_modules/azure-functions-core-tools
> node lib/install.js

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/azure-functions-core-tools/bin'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@2.0.1-beta.22 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@2.0.1-beta.22 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee212/.npm/_logs/2017-12-09T20_22_13_012Z-debug.log
```

and I tried again with `2.0.1-beta1.15`
```
$ sudo npm i -g azure-functions-core-tools@2.0.1-beta1.15
/usr/local/bin/azfun -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/func -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azurefunctions -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js

> azure-functions-core-tools@2.0.1-beta1.15 postinstall /usr/local/lib/node_modules/azure-functions-core-tools
> node lib/install.js

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/home/lee212/.azurefunctions'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@2.0.1-beta1.15 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@2.0.1-beta1.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee212/.npm/_logs/2017-12-09T20_44_17_323Z-debug.log
```

When I manually created the `.azurefunctions` directory at my HOME, it installed successfully.

FYI, I have Ubuntu 16.04 LTS, .NET 2.0.2, npm 5.6.0,  node 8.8.1 and az CLI installed.

**Comment by ahmelsayed** [comment]
on Unix machines, you need to do `sudo npm i -g azure-functions-core-tools@core --unsafe-perm`

Out npm package just contains this [install script](https://github.com/Azure/azure-functions-cli/blob/core/src/Azure.Functions.Cli/npm/lib/install.js) which as you can see needs to download a zip file and unzip it to the node_modules folder of the package. 
On Unix machines, npm changes the user for install script from `su` to `nobody` after the sudo part is done, and `nobody` doesn't have permissions on that dir. `--unsafe-perm` tells npm to run the install script as sudo as well.

**Comment by nelak** [comment]
Another option is to use Node with [Node Version Manager](http://nvm.sh) which doesn't require sudo for `npm install -g packageName` and allows running multiple node environments.

**Comment by lee212** [comment]
I see, the article that I followed ([Code and test Azure Functions locally](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#version-2x-runtime) ) told me that I run the installation command without the `--unsafe-perm` option on Ubuntu. I probably should used `nvm` but deactivated it while I was installing this tool.

**Comment by ahmelsayed** [comment]
I'm not sure why the article was calling Ubuntu out in particular. Ubuntu should behave the same as any other linux distro. 
I opened a PR https://github.com/MicrosoftDocs/azure-docs/compare/master...ahmelsayed:patch-1
