### ISSUE TITLE
Add a --no-interactive switch to func host start and func run to enable integration testing

### ISSUE THREAD

**Issue by jonathanfishbein1** [Azure/azure-functions-cli#93]
With a -Nointeractive flag to facilitate CI.  Currently vsts build agent is throwing error
'This operation requires an interactive window station'

**Comment by lindydonna** [comment]
@jonathanfishbein1 What is the scenario where you want this?  Do you want to run tests in a non-interactive session?

**Comment by jonathanfishbein1** [comment]
@lindydonna 
Yes I want to func host start and then run integration tests with WebRequest against it.
