### ISSUE TITLE
func init incorrectly detected a git repo

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#97]
in cmd I gloably installed latest cli , created a new dir and ran ```func init```

Output is
```bash
Writing .gitignore
Writing host.json
Writing appsettings.json
Created launch.json
Directory already a git repository.
```

The directory is NOT a git repo. I wonder if getting confused by the .gitignore file?

**Comment by lindydonna** [comment]
@SteveALee Is there a subdirectory that's a Git repo?  The CLI calls out to Git to determine whether the current directory is a git repo.

**Comment by SteveALee** [comment]
hmm didn't check that just "dir /a" in CD looking for .git. will look.

Steve Lee
OpenDirective http://opendirective.com

**Comment by ahmelsayed** [comment]
we [call](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs#L117) [`git rev-parse --git-dir`](https://git-scm.com/docs/git-rev-parse) to check if the current directory is within a git repo.

**Comment by SteveALee** [comment]
Aha yes! `git rev-parse --git-dir` shows I have a useless .git in my project root - no idea why it's there.

**Comment by SteveALee** [comment]
Out of interest WHY does it do a git init? Surely that is out of scope and makes assumptions - I might use mercury or sourcesafe :)

**Comment by ahmelsayed** [comment]
Somewhere in [here](https://en.wikipedia.org/wiki/Likelihood_function) lies an answer :) 
Though yes, I should add an option for no source control. I initially [intended](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Actions/LocalActions/InitAction.cs#L71-L74) to have source control optional, but never got around to fully implementing it.
