### ISSUE TITLE
Add documentation for --cors setting in readme and command line

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-cli#98]
My HTTP function is available at
```http://localhost:7071/api/getAlbumList2```
and I'm calling it from my client code running at
```http://localhost:8000```

but I get 400 {'Message":"The origin 'http://localhost:8000' is not allowed."}'

which is a CORS failure.

I can't figure how to set allowable origins in the CLI so I can test my function (which works fine on Azure with the same origin)

**Comment by SteveALee** [comment]
So now I got my Google foo back I found this is covered by Azure/azure-webjobs-sdk-script#1012

It needs to be added to 
* the CLI README and other docs
* the ```func functionapp``` usage

**Comment by lindydonna** [comment]
@SteveALee thanks for filing!

**Comment by SteveALee** [comment]
+1
